// @vitest-environment jsdom
/**
 * Security contract: sanitize custom `<head>` code before export injection.
 *
 * Closes the LATENT STORED-XSS vector flagged in the Phase 0 audit (L1).
 * Prior to this sanitizer, settings.head was persisted raw and injected
 * verbatim — `<script>alert(1)</script>` with matching tag counts passed
 * the naive validator in usePageSettings.
 *
 * @license BSD-3-Clause
 */

import { describe, it, expect } from "vitest";
import { sanitizeHeadCode } from "../sanitizeHeadCode";

describe("sanitizeHeadCode — XSS defense", () => {
  it("strips inline <script>alert()</script>", () => {
    const raw = `<script>alert('xss')</script><meta name="x" content="y">`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("alert");
    expect(clean).not.toMatch(/<script>[^<]*<\/script>/i);
    // The legitimate meta tag survives.
    expect(clean).toContain('<meta');
  });

  it("strips <script> with javascript: src", () => {
    const raw = `<script src="javascript:alert(1)"></script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean.toLowerCase()).not.toContain("javascript:");
  });

  it("strips event handler attributes (onload, onclick, onerror)", () => {
    const raw = `<meta onload="alert(1)" name="description" content="ok">`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("onload");
    expect(clean).not.toContain("alert");
    expect(clean).toContain('name="description"');
    expect(clean).toContain('content="ok"');
  });

  it("keeps allowlisted <script src=...> with integrity", () => {
    const raw = `<script src="https://plausible.io/js/script.js" integrity="sha384-abc" async></script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).toContain("https://plausible.io/js/script.js");
    expect(clean).toContain("integrity");
    expect(clean).toContain("async");
  });

  it("keeps <link rel=preconnect> and <meta name>", () => {
    // Note: DOMPurify's default profile strips `property` from <meta>. Open
    // Graph tags are generated by SEOInjector.inject() from settings.seo,
    // not from custom head code, so this is fine. Users who want to inject
    // custom OG should edit Social settings, not paste into Custom Head Code.
    const raw = `
      <link rel="preconnect" href="https://fonts.bunny.net">
      <link rel="stylesheet" href="https://fonts.bunny.net/css?family=inter">
      <meta name="description" content="Acme site">
    `;
    const clean = sanitizeHeadCode(raw);
    expect(clean).toContain('rel="preconnect"');
    expect(clean).toContain("fonts.bunny.net");
    expect(clean).toContain('name="description"');
    expect(clean).toContain('content="Acme site"');
  });

  it("strips disallowed tags (iframe, form, style with bad content)", () => {
    const raw = `<iframe src="https://evil.example"></iframe><form action="x"></form>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("<iframe");
    expect(clean).not.toContain("<form");
  });

  it("returns '' for empty/whitespace/nullish input", () => {
    expect(sanitizeHeadCode("")).toBe("");
    expect(sanitizeHeadCode("   \n\t  ")).toBe("");
    expect(sanitizeHeadCode(null)).toBe("");
    expect(sanitizeHeadCode(undefined)).toBe("");
  });

  it("strips <script> without src (inline JS) — belt-and-suspenders", () => {
    // Even if ALLOWED_TAGS contains "script", the uponSanitizeElement hook
    // removes any <script> missing a src attribute.
    const raw = `<script>var x = 1;</script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("var x");
    expect(clean).not.toMatch(/<script>[^<]*<\/script>/i);
  });

  it("blocks </script> injection inside JSON-LD structured data use cases", () => {
    // Simulates a user pasting structured data that tries to escape the
    // <script type="application/ld+json"> wrapper we use elsewhere.
    const raw = `<script type="application/ld+json" src="./data.json"></script>`;
    const clean = sanitizeHeadCode(raw);
    // Src-bearing script is allowed; the closing tag is fine here because
    // we emit the clean output verbatim and it's already well-formed.
    expect(clean).toContain("application/ld+json");
    expect(clean).toContain("./data.json");
  });
});
