// @vitest-environment jsdom
/**
 * Security contract: sanitize custom `<head>` code before export injection.
 *
 * Closes the LATENT STORED-XSS vector flagged in the Phase 0 audit (L1).
 * Prior to this sanitizer, settings.head was persisted raw and injected
 * verbatim — `<script>alert(1)</script>` with matching tag counts passed
 * the naive validator in usePageSettings.
 *
 * @license BSD-3-Clause
 */

import { describe, it, expect } from "vitest";
import { sanitizeHeadCode } from "../sanitizeHeadCode";

describe("sanitizeHeadCode — XSS defense", () => {
  it("strips inline <script>alert()</script>", () => {
    const raw = `<script>alert('xss')</script><meta name="x" content="y">`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("alert");
    expect(clean).not.toMatch(/<script>[^<]*<\/script>/i);
    // The legitimate meta tag survives.
    expect(clean).toContain('<meta');
  });

  it("strips <script> with javascript: src", () => {
    const raw = `<script src="javascript:alert(1)"></script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean.toLowerCase()).not.toContain("javascript:");
  });

  it("strips event handler attributes (onload, onclick, onerror)", () => {
    const raw = `<meta onload="alert(1)" name="description" content="ok">`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("onload");
    expect(clean).not.toContain("alert");
    expect(clean).toContain('name="description"');
    expect(clean).toContain('content="ok"');
  });

  it("keeps allowlisted <script src=...> with integrity", () => {
    const raw = `<script src="https://plausible.io/js/script.js" integrity="sha384-abc" async></script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).toContain("https://plausible.io/js/script.js");
    expect(clean).toContain("integrity");
    expect(clean).toContain("async");
  });

  it("keeps <link rel=preconnect> and <meta name>", () => {
    // Note: DOMPurify's default profile strips `property` from <meta>. Open
    // Graph tags are generated by SEOInjector.inject() from settings.seo,
    // not from custom head code, so this is fine. Users who want to inject
    // custom OG should edit Social settings, not paste into Custom Head Code.
    const raw = `
      <link rel="preconnect" href="https://fonts.bunny.net">
      <link rel="stylesheet" href="https://fonts.bunny.net/css?family=inter">
      <meta name="description" content="Acme site">
    `;
    const clean = sanitizeHeadCode(raw);
    expect(clean).toContain('rel="preconnect"');
    expect(clean).toContain("fonts.bunny.net");
    expect(clean).toContain('name="description"');
    expect(clean).toContain('content="Acme site"');
  });

  it("strips disallowed tags (iframe, form, style with bad content)", () => {
    const raw = `<iframe src="https://evil.example"></iframe><form action="x"></form>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("<iframe");
    expect(clean).not.toContain("<form");
  });

  it("returns '' for empty/whitespace/nullish input", () => {
    expect(sanitizeHeadCode("")).toBe("");
    expect(sanitizeHeadCode("   \n\t  ")).toBe("");
    expect(sanitizeHeadCode(null)).toBe("");
    expect(sanitizeHeadCode(undefined)).toBe("");
  });

  it("strips <script> without src (inline JS) — belt-and-suspenders", () => {
    // Even if ALLOWED_TAGS contains "script", the uponSanitizeElement hook
    // removes any <script> missing a src attribute.
    const raw = `<script>var x = 1;</script>`;
    const clean = sanitizeHeadCode(raw);
    expect(clean).not.toContain("var x");
    expect(clean).not.toMatch(/<script>[^<]*<\/script>/i);
  });

  it("blocks </script> injection inside JSON-LD structured data use cases", () => {
    // Simulates a user pasting structured data that tries to escape the
    // <script type="application/ld+json"> wrapper we use elsewhere.
    const raw = `<script type="application/ld+json" src="./data.json"></script>`;
    const clean = sanitizeHeadCode(raw);
    // Src-bearing script is allowed; the closing tag is fine here because
    // we emit the clean output verbatim and it's already well-formed.
    expect(clean).toContain("application/ld+json");
    expect(clean).toContain("./data.json");
  });
});

describe("sanitizeHeadCode — allowlist coverage (extension)", () => {
  it("CURRENT BEHAVIOR: keeps <style> but strips its CSS body", () => {
    // KEEP_CONTENT: false drops the text content even of allowlisted tags in
    // this head-context profile — the tag shell survives, the CSS does not.
    const clean = sanitizeHeadCode(`<style>body{background:#fff}</style>`);
    expect(clean).toContain("<style>");
    expect(clean).not.toContain("background:#fff");
  });

  it.todo(
    "BUG(policy drift): <style> is on the module's ALLOW list but its CSS body is " +
      "stripped (KEEP_CONTENT: false empties allowlisted text-content tags), making " +
      "pasted <style> blocks useless. Same for <title> text."
  );

  it("CURRENT BEHAVIOR: keeps <title> but strips its text", () => {
    const clean = sanitizeHeadCode(`<title>My Site</title>`);
    expect(clean).toContain("<title>");
    expect(clean).not.toContain("My Site");
  });

  it("keeps <noscript> wrappers", () => {
    const clean = sanitizeHeadCode(
      `<noscript><link rel="stylesheet" href="/fallback.css"></noscript>`
    );
    expect(clean).toContain("<noscript>");
    expect(clean).toContain("/fallback.css");
  });

  it("CURRENT BEHAVIOR: strips `property` from <meta> despite the force-allow hook", () => {
    // sanitizeHeadCode.ts registers an uponSanitizeAttribute hook + ADD_ATTR
    // claiming to preserve `property` (Open Graph), but observed behavior is
    // that DOMPurify still strips it from <meta>. OG tags are generated by
    // SEOInjector from settings.seo, so exports are unaffected — but the
    // source comments overpromise.
    const clean = sanitizeHeadCode(`<meta property="og:title" content="Acme">`);
    expect(clean).not.toContain("property=");
    expect(clean).toContain('content="Acme"');
  });

  it.todo(
    "BUG(dead code / doc drift): the ATTR_FORCE_ALLOW uponSanitizeAttribute hook and " +
      "ADD_ATTR: ['property', ...] in sanitizeHeadCode.ts do not actually preserve " +
      "`property` on <meta> — the attribute is still stripped. Either fix the hook or " +
      "delete it and the comments claiming OG meta survives."
  );

  it("keeps <meta http-equiv> and <meta charset>", () => {
    const clean = sanitizeHeadCode(
      `<meta http-equiv="refresh" content="30"><meta charset="utf-8">`
    );
    expect(clean).toContain('http-equiv="refresh"');
    expect(clean).toContain('charset="utf-8"');
  });

  it("CURRENT BEHAVIOR: strips style= but keeps data-* attributes", () => {
    // DOMPurify defaults ALLOW_DATA_ATTR: true, so data-* survives even though
    // it is not in ALLOWED_HEAD_ATTRS. Inert for head tags, but diverges from
    // the module doc's "any unknown attribute" BLOCK policy.
    const clean = sanitizeHeadCode(
      `<meta name="x" content="y" data-evil="1" style="color:red">`
    );
    expect(clean).not.toContain("style=");
    expect(clean).toContain('data-evil="1"');
    expect(clean).toContain('name="x"');
    expect(clean).toContain('content="y"');
  });

  it.todo(
    "BUG(policy drift): module doc says any unknown attribute is BLOCKED, but data-* " +
      "attributes pass through (DOMPurify default ALLOW_DATA_ATTR: true is not disabled). " +
      "Set ALLOW_DATA_ATTR: false to match the stated policy."
  );

  it("CURRENT BEHAVIOR: a body-level element ends <head> parsing — everything after it is dropped", () => {
    // The HTML parser closes <head> at <div>, so the trailing <meta> lands in
    // <body> and head-innerHTML extraction returns ''. Fails in the safe
    // direction (drops too much rather than too little).
    const clean = sanitizeHeadCode(`<div>leaked text</div><meta name="k" content="v">`);
    expect(clean).toBe("");
  });

  it("strips <script> whose src is a whitespace-padded/mixed-case javascript: URI", () => {
    const clean = sanitizeHeadCode(`<script src="  JavaScript:alert(1)"></script>`);
    expect(clean.toLowerCase()).not.toContain("javascript:");
    expect(clean).not.toContain("alert");
  });

  it("returns '' when input contains only disallowed content", () => {
    expect(sanitizeHeadCode(`<div><span>nope</span></div>`)).toBe("");
    expect(sanitizeHeadCode(`<script>alert(1)</script>`)).toBe("");
  });

  it("trims surrounding whitespace from the extracted head fragment", () => {
    const clean = sanitizeHeadCode(`\n\n   <meta name="a" content="b">   \n`);
    expect(clean.startsWith("<meta")).toBe(true);
    expect(clean.endsWith(">")).toBe(true);
  });

  it("preserves multiple allowlisted tags in input order", () => {
    const clean = sanitizeHeadCode(
      `<meta name="first" content="1"><link rel="canonical" href="https://x.example"><title>T</title>`
    );
    expect(clean.indexOf('name="first"')).toBeGreaterThanOrEqual(0);
    expect(clean.indexOf('name="first"')).toBeLessThan(clean.indexOf('rel="canonical"'));
    expect(clean.indexOf('rel="canonical"')).toBeLessThan(clean.indexOf("<title>"));
  });
});
