/**
 * Shared styles for Pro Inspector controls — ported to --bd-* tokens.
 * Single source of truth for inline control styling consumed by legacy
 * per-section components that don't yet use .bdi-* CSS classes directly.
 *
 * Reference: /design-system/preview/comp-inspector.v1.html
 *
 * @license BSD-3-Clause
 */

import type * as React from "react";

export const baseStyles = {
  section: {
    borderBottom: "1px solid var(--bd-border)",
  },
  sectionHeader: (isOpen: boolean): React.CSSProperties => ({
    width: "100%",
    padding: "9px 12px",
    background: "transparent",
    border: "none",
    color: isOpen ? "var(--bd-fg-primary)" : "var(--bd-fg-secondary)",
    font: `600 10px var(--bd-font)`,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    transition: "color 120ms",
  }),
  sectionContent: {
    padding: "6px 12px 12px",
  },
  row: {
    display: "grid" as const,
    gridTemplateColumns: "44px 1fr",
    alignItems: "center" as const,
    gap: 6,
    marginBottom: 6,
  },
  label: {
    font: `500 11px var(--bd-font)`,
    color: "var(--bd-fg-secondary)",
    letterSpacing: "-0.005em",
    minWidth: 44,
    flexShrink: 0,
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 4,
  },
  input: {
    flex: 1,
    height: 24,
    padding: "0 8px",
    background: "var(--bd-bg-subtle)",
    border: "1px solid transparent",
    borderRadius: 4,
    color: "var(--bd-fg-primary)",
    font: `500 11.5px var(--bd-font)`,
    outline: "none",
    transition: "background 120ms, border-color 120ms",
  },
  inputFocus: {
    background: "#fff",
    borderColor: "var(--bd-accent)",
    boxShadow: "0 0 0 2px rgba(45, 109, 255, 0.12)",
  },
  select: {
    flex: 1,
    height: 24,
    padding: "0 24px 0 8px",
    background: "var(--bd-bg-subtle)",
    border: "1px solid transparent",
    borderRadius: 4,
    color: "var(--bd-fg-primary)",
    font: `500 11.5px var(--bd-font)`,
    outline: "none",
    cursor: "pointer",
    appearance: "none" as const,
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 24 24' fill='none' stroke='%2394A3B8' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 8px center",
  },
  buttonGroup: {
    display: "grid" as const,
    gridAutoFlow: "column" as const,
    gridAutoColumns: "1fr",
    gap: 0,
    background: "var(--bd-bg-subtle)",
    borderRadius: 4,
    padding: 2,
    height: 24,
  },
  buttonGroupItem: (active: boolean): React.CSSProperties => ({
    padding: 0,
    background: active ? "#fff" : "transparent",
    border: "none",
    borderRadius: 3,
    color: active ? "var(--bd-fg-heading)" : "var(--bd-fg-secondary)",
    font: `${active ? 600 : 500} 11px var(--bd-font)`,
    cursor: "pointer",
    transition: "background 120ms, color 120ms",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    boxShadow: active ? "0 1px 2px rgba(15, 23, 42, 0.08)" : "none",
  }),
  compactBtn: (active: boolean): React.CSSProperties => ({
    flex: 1,
    height: 22,
    padding: "0 4px",
    background: active ? "var(--bd-accent-tint)" : "var(--bd-bg-subtle)",
    border: active ? "1px solid rgba(45, 109, 255, 0.25)" : "1px solid transparent",
    borderRadius: 3,
    color: active ? "var(--bd-accent)" : "var(--bd-fg-secondary)",
    font: `500 11px var(--bd-font)`,
    cursor: "pointer",
  }),
  sectionTitle: {
    font: `600 9px var(--bd-font)`,
    letterSpacing: "0.08em",
    color: "var(--bd-fg-muted)",
    textTransform: "uppercase" as const,
    marginBottom: 4,
    marginTop: 2,
  },
  colorInput: {
    width: 20,
    height: 20,
    padding: 0,
    border: "none",
    borderRadius: 3,
    cursor: "pointer",
    overflow: "hidden" as const,
    boxShadow: "inset 0 0 0 1px rgba(15, 23, 42, 0.10)",
  },
  unitSelect: {
    width: 44,
    height: 24,
    padding: "0 4px",
    background: "transparent",
    border: "none",
    color: "var(--bd-fg-muted)",
    font: `500 10px var(--bd-font)`,
    outline: "none",
    cursor: "pointer",
    textTransform: "lowercase" as const,
  },
  inputWithUnit: {
    flex: 1,
    height: 24,
    padding: "0 4px 0 8px",
    background: "transparent",
    border: "none",
    color: "var(--bd-fg-primary)",
    font: `500 11.5px var(--bd-font)`,
    outline: "none",
    fontVariantNumeric: "tabular-nums" as const,
  },
  slider: {
    flex: 1,
    height: 4,
    background: "var(--bd-border-medium)",
    borderRadius: 2,
    appearance: "none" as const,
    cursor: "pointer",
  },
};
