/**
 * An inserted image must carry the asset's alt text.
 *
 * `insertMediaAt` created the element with `attributes: { src }` and nothing
 * else, so alt text — typed by hand, generated by AI, synced to the server —
 * had no output at all: every published image shipped with no alt.
 *
 * @license BSD-3-Clause
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import {
  createTestComposer,
  installEngineBrowserStubs,
  removeEngineBrowserStubs,
} from "./test-utils/realComposer";

beforeAll(installEngineBrowserStubs);
afterAll(removeEngineBrowserStubs);

function setup() {
  const composer = createTestComposer();
  composer.elements.createPage("Home");
  return composer;
}

describe("insertMediaAt — alt text", () => {
  it("puts the asset's alt text on a newly created image", () => {
    const composer = setup();
    const result = composer.elements.insertMediaAt("https://cdn/x.png", "image", {
      alt: "A red bicycle against a wall",
    });
    expect(result?.kind).toBe("element");
    const el = composer.elements.getElement((result as { elementId: string }).elementId);
    expect(el?.getAttribute("alt")).toBe("A red bicycle against a wall");
    expect(el?.getAttribute("src")).toBe("https://cdn/x.png");
  });

  it("omits the attribute entirely when the asset has no alt text", () => {
    const composer = setup();
    const result = composer.elements.insertMediaAt("https://cdn/y.png", "image");
    const el = composer.elements.getElement((result as { elementId: string }).elementId);
    expect(el?.getAttribute("alt")).toBeUndefined();
  });

  it("carries alt when replacing an existing element's src", () => {
    const composer = setup();
    const first = composer.elements.insertMediaAt("https://cdn/a.png", "image");
    const id = (first as { elementId: string }).elementId;

    composer.elements.insertMediaAt("https://cdn/b.png", "image", {
      targetElementId: id,
      alt: "Replacement description",
    });

    const el = composer.elements.getElement(id);
    expect(el?.getAttribute("src")).toBe("https://cdn/b.png");
    expect(el?.getAttribute("alt")).toBe("Replacement description");
  });
});
