-- No-op. Originally added projectStyles/Assets/Settings JSONB columns to "sites".
-- Those columns are now part of the 20260101000000_initial_baseline migration.
-- This file remains as historical placeholder so _prisma_migrations rows align.
