/**
 * Elements tab data constants — block icons, descriptions, categories
 * Extracted from ElementsTab.tsx to keep the main file under 500 lines.
 * @license BSD-3-Clause
 */

import {
  LayoutTemplate,
  Square,
  Columns2,
  Columns3,
  Grid3x3,
  Rows3,
  AlignHorizontalSpaceBetween,
  Heading,
  AlignLeft,
  Type,
  Link,
  List,
  Minus,
  Image,
  Video,
  Music,
  Smile,
  Play,
  Map,
  FormInput,
  TextCursorInput,
  CheckSquare,
  Circle,
  ChevronDown,
  Upload,
  Calendar,
  Clock,
  Mail,
  Lock,
  Hash,
  SlidersHorizontal,
  Palette,
  Tag,
  Send,
  MousePointerClick,
  CreditCard,
  Star,
  MessageSquare,
  DollarSign,
  Timer,
  ChevronsUpDown,
  Share2,
  ShoppingCart,
  Package,
  FileImage,
  Sparkles,
  GalleryHorizontal,
  Menu,
  Megaphone,
  Box,
  Layers,
  LayoutList,
  ToggleLeft,
  PanelTop,
  Maximize2,
  Table2,
  type LucideIcon,
} from "lucide-react";

// ─── Storage keys ─────────────────────────────────────────────────────────────

export const RECENT_STORAGE_KEY = "aqb-elements-recent";
export const FAVORITES_STORAGE_KEY = "aqb-elements-favorites";
export const TIP_DISMISSED_KEY = "aqb-elements-tip-dismissed";
export const EXPANDED_CATEGORY_KEY = "aqb-elements-expanded-category";
export const MAX_RECENT = 8;
export const MOST_USED_IDS = [
  "section",
  "grid",
  "flex",
  "button",
  "card",
  "image",
  "heading",
  "paragraph",
];

// ─── Category ordering & remapping ───────────────────────────────────────────

export const NEW_CATEGORY_ORDER = [
  "Most Used",
  "Layout",
  "Basic",
  "Typography",
  "Media",
  "Forms",
  "Advanced",
];

export const CATEGORY_REMAP: Record<string, string> = {
  Layout: "Layout",
  Basic: "Basic",
  Media: "Media",
  Forms: "Forms",
  Sections: "Advanced",
  Components: "Advanced",
  Ecommerce: "Advanced",
  Other: "Typography",
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "Most Used": Sparkles,
  Layout: Layers,
  Basic: Box,
  Typography: Type,
  Media: Image,
  Forms: FormInput,
  Advanced: Grid3x3,
};

// ─── Block icon mapping ───────────────────────────────────────────────────────

export const BLOCK_ICONS: Record<string, LucideIcon> = {
  container: LayoutTemplate,
  section: Square,
  columns: Columns2,
  columns3: Columns3,
  grid: Grid3x3,
  flex: AlignHorizontalSpaceBetween,
  row: Rows3,
  column: Square,
  spacer: Minus,
  heading: Heading,
  paragraph: AlignLeft,
  text: Type,
  link: Link,
  list: List,
  divider: Minus,
  image: Image,
  video: Video,
  audio: Music,
  icon: Smile,
  svg: FileImage,
  lottie: Sparkles,
  gallery: GalleryHorizontal,
  "video-embed": Play,
  "map-embed": Map,
  form: FormInput,
  input: TextCursorInput,
  textarea: AlignLeft,
  select: ChevronDown,
  checkbox: CheckSquare,
  radio: Circle,
  "file-input": Upload,
  "date-input": Calendar,
  "time-input": Clock,
  "email-input": Mail,
  "password-input": Lock,
  "number-input": Hash,
  "range-input": SlidersHorizontal,
  "color-input": Palette,
  label: Tag,
  "submit-button": Send,
  button: MousePointerClick,
  card: CreditCard,
  testimonial: MessageSquare,
  pricing: DollarSign,
  progress: SlidersHorizontal,
  countdown: Timer,
  accordion: ChevronsUpDown,
  social: Share2,
  slider: SlidersHorizontal,
  hero: Star,
  stack: LayoutList,
  switch: ToggleLeft,
  tabs: PanelTop,
  modal: Maximize2,
  table: Table2,
  features: Grid3x3,
  footer: Square,
  navbar: Menu,
  cta: Megaphone,
  "product-card": Package,
  "product-grid": Grid3x3,
  "product-detail": Package,
  "cart-button": ShoppingCart,
};

// ─── Block descriptions ───────────────────────────────────────────────────────

export const BLOCK_DESCRIPTIONS: Record<string, string> = {
  section: "Full width container",
  columns: "Split layout 50/50",
  columns3: "Evenly distributed",
  grid: "Auto-layout grid",
  flex: "Advanced alignment control",
  container: "Generic wrapper",
  row: "Horizontal stack",
  column: "Vertical stack",
  spacer: "Empty spacing element",
  heading: "H1-H6 titles",
  paragraph: "Body text element",
  text: "Inline text element",
  link: "Clickable hyperlink",
  list: "Ordered/unordered list",
  divider: "Horizontal separator",
  image: "Image with lazy load",
  video: "Self-hosted video",
  audio: "Audio player",
  icon: "SVG icon library",
  svg: "Custom SVG upload",
  lottie: "Lottie animation",
  gallery: "Image carousel",
  "video-embed": "YouTube, Vimeo embed",
  "map-embed": "Google Maps embed",
  form: "Form container",
  input: "Text input field",
  textarea: "Multi-line text",
  select: "Dropdown select",
  checkbox: "Checkbox input",
  radio: "Radio button group",
  "file-input": "File upload field",
  "date-input": "Date picker",
  "time-input": "Time picker",
  "email-input": "Email field",
  "password-input": "Password field",
  "number-input": "Number field",
  "range-input": "Slider input",
  "color-input": "Color picker",
  label: "Form label",
  "submit-button": "Form submit",
  button: "Interactive button",
  card: "Content card wrapper",
  testimonial: "Customer review",
  pricing: "Pricing table card",
  progress: "Progress indicator",
  countdown: "Timer countdown",
  accordion: "Expandable content",
  social: "Social media links",
  slider: "Image/content slider",
  hero: "Hero section layout",
  stack: "Flex stack container",
  switch: "Toggle switch",
  tabs: "Tabbed content",
  modal: "Popup modal dialog",
  table: "Data table",
  features: "Feature grid section",
  footer: "Footer section",
  navbar: "Navigation bar",
  cta: "Call to action",
  "product-card": "E-commerce product",
  "product-grid": "Product listing",
  "product-detail": "Product page",
  "cart-button": "Add to cart",
};
