/**
 * AssetDetailsPanel — P7 alt text section tests.
 *
 * Covers: editor render, user-typed edit triggers onUpdateAltText, provenance
 * chip visibility, Regenerate button states (idle / generating / success /
 * skipped / error), non-image hides the section, missing handlers hide it.
 *
 * @license BSD-3-Clause
 */

import { render, fireEvent, waitFor, act } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import * as React from "react";
import { AssetDetailsPanel } from "../AssetDetailsPanel";
import type { LibraryItem } from "../../../sidebar/tabs/media/data/mediaTypes";

function makeImage(overrides: Partial<LibraryItem> = {}): LibraryItem {
  return {
    key: "asset-1",
    name: "photo.jpg",
    type: "img",
    src: "https://blob.example/photo.jpg",
    size: 12345,
    mimeType: "image/jpeg",
    createdAt: "2026-05-09T00:00:00Z",
    ...overrides,
  };
}

function renderPanel(overrides: Partial<React.ComponentProps<typeof AssetDetailsPanel>> = {}) {
  const composer = {
    mediaOps: { replaceAcross: vi.fn(), getUsages: vi.fn(() => ({ count: 0, places: [] })) },
  } as any;
  const props = {
    selectedItem: makeImage(),
    versions: [],
    usageCount: 0,
    libraryItems: [],
    onSelectAsset: vi.fn(),
    onInsert: vi.fn(),
    onEditImage: vi.fn(),
    onOpenRename: vi.fn(),
    onRequestDelete: vi.fn(),
    composer,
    addToast: vi.fn(),
    onUpdateAltText: vi.fn(),
    onRegenerateAltText: vi.fn(),
    ...overrides,
  };
  return { ...render(<AssetDetailsPanel {...props} />), props };
}

describe("AssetDetailsPanel — alt text section (P7)", () => {
  it("renders the alt-text section for image assets when handlers are provided", () => {
    const { getByTestId } = renderPanel();
    expect(getByTestId("alt-text-section")).toBeTruthy();
  });

  it("shows current alt text in the textarea", () => {
    const { container } = renderPanel({
      selectedItem: makeImage({ altText: "A red bicycle." }),
    });
    const textarea = container.querySelector("textarea") as HTMLTextAreaElement;
    expect(textarea).toBeTruthy();
    expect(textarea.value).toBe("A red bicycle.");
  });

  it("calls onUpdateAltText with the new value when the user types", () => {
    const onUpdateAltText = vi.fn();
    const { container } = renderPanel({ onUpdateAltText });
    const textarea = container.querySelector("textarea") as HTMLTextAreaElement;
    fireEvent.change(textarea, { target: { value: "User typed this" } });
    expect(onUpdateAltText).toHaveBeenCalledWith("asset-1", "User typed this");
  });

  it("enforces the 125-char max via maxLength attribute", () => {
    const { container } = renderPanel();
    const textarea = container.querySelector("textarea") as HTMLTextAreaElement;
    expect(textarea.maxLength).toBe(125);
  });

  it("shows a character counter when no provenance is set", () => {
    const { getByText } = renderPanel({
      selectedItem: makeImage({ altText: "Hello" }),
    });
    expect(getByText("5 / 125")).toBeTruthy();
  });

  it("shows the AI provenance chip when generatedAltMeta is set", () => {
    const { getByTestId, queryByText } = renderPanel({
      selectedItem: makeImage({
        altText: "A red bicycle by a brick wall.",
        generatedAltMeta: {
          generatedAt: "2026-05-09T12:00:00Z",
          model: "claude-haiku-4-5",
        },
      }),
    });
    const chip = getByTestId("alt-text-provenance");
    expect(chip.textContent).toMatch(/AI-generated by claude-haiku-4-5/);
    // Counter is suppressed when chip shows
    expect(queryByText(/\/ 125$/)).toBeNull();
  });

  it("renders 'Generate' label when there is no AI provenance and no alt text", () => {
    const { getByTestId } = renderPanel();
    const button = getByTestId("alt-text-regenerate");
    expect(button.textContent).toMatch(/Generate/);
    expect(button.textContent).not.toMatch(/Regenerate/);
  });

  it("renders 'Regenerate' label when AI provenance is present", () => {
    const { getByTestId } = renderPanel({
      selectedItem: makeImage({
        altText: "A red bicycle.",
        generatedAltMeta: { generatedAt: "2026-05-09T12:00:00Z", model: "claude-haiku-4-5" },
      }),
    });
    const button = getByTestId("alt-text-regenerate");
    expect(button.textContent).toMatch(/Regenerate/);
  });

  it("calls onRegenerateAltText with the asset key when clicked, and toasts on success", async () => {
    const onRegenerateAltText = vi.fn().mockResolvedValue({
      altText: "Generated alt text.",
      skipped: false,
    });
    const addToast = vi.fn();
    const { getByTestId } = renderPanel({ onRegenerateAltText, addToast });

    await act(async () => {
      fireEvent.click(getByTestId("alt-text-regenerate"));
    });

    expect(onRegenerateAltText).toHaveBeenCalledWith("asset-1");
    await waitFor(() => {
      expect(addToast).toHaveBeenCalledWith(
        expect.objectContaining({ description: expect.stringMatching(/regenerated/i), tone: "success" }),
      );
    });
  });

  it("toasts info when the server skipped overwriting user-typed alt text", async () => {
    const onRegenerateAltText = vi.fn().mockResolvedValue({
      altText: "User typed this",
      skipped: true,
    });
    const addToast = vi.fn();
    const { getByTestId } = renderPanel({ onRegenerateAltText, addToast });

    await act(async () => {
      fireEvent.click(getByTestId("alt-text-regenerate"));
    });

    await waitFor(() => {
      expect(addToast).toHaveBeenCalledWith(
        expect.objectContaining({ description: expect.stringMatching(/kept your alt text/i), tone: "info" }),
      );
    });
  });

  it("toasts error when onRegenerateAltText returns null (auth/network)", async () => {
    const onRegenerateAltText = vi.fn().mockResolvedValue(null);
    const addToast = vi.fn();
    const { getByTestId } = renderPanel({ onRegenerateAltText, addToast });

    await act(async () => {
      fireEvent.click(getByTestId("alt-text-regenerate"));
    });

    await waitFor(() => {
      expect(addToast).toHaveBeenCalledWith(
        expect.objectContaining({ tone: "error" }),
      );
    });
  });

  it("disables the Regenerate button while the request is in flight", async () => {
    let resolve: (v: any) => void = () => {};
    const onRegenerateAltText = vi.fn(
      () => new Promise<{ altText: string; skipped: boolean }>((r) => { resolve = r; }),
    );
    const { getByTestId } = renderPanel({ onRegenerateAltText });
    const button = getByTestId("alt-text-regenerate") as HTMLButtonElement;

    await act(async () => {
      fireEvent.click(button);
    });

    expect(button.disabled).toBe(true);
    expect(button.textContent).toMatch(/Generating/);

    await act(async () => {
      resolve({ altText: "done", skipped: false });
      // Let the resolution propagate.
      await Promise.resolve();
      await Promise.resolve();
    });

    await waitFor(() => {
      expect(button.disabled).toBe(false);
    });
  });

  it("hides the alt-text section for non-image assets (videos, fonts, icons)", () => {
    for (const type of ["vid", "fnt", "ico"] as const) {
      const { queryByTestId, unmount } = renderPanel({
        selectedItem: makeImage({ key: `${type}-key`, type }),
      });
      expect(queryByTestId("alt-text-section")).toBeNull();
      unmount();
    }
  });

  it("hides the alt-text section when onUpdateAltText is not provided", () => {
    const { queryByTestId } = renderPanel({ onUpdateAltText: undefined });
    expect(queryByTestId("alt-text-section")).toBeNull();
  });
});
