/**
 * Icon categories 1-9: Arrows, Actions, Interface, Users, Communication, Media, Files, Text, Time
 *
 * @module constants/iconCategories1
 * @license BSD-3-Clause
 */

import {
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  Undo2,
  Redo2,
  RefreshCw,
  RefreshCcw,
  RotateCw,
  RotateCcw,
  Plus,
  Minus,
  X,
  Check,
  Search,
  Edit,
  Edit2,
  Edit3,
  Trash,
  Trash2,
  Copy,
  Clipboard,
  ClipboardCopy,
  ClipboardPaste,
  Download,
  Upload,
  Save,
  Share,
  Share2,
  ExternalLink,
  MoreHorizontal,
  MoreVertical,
  Grip,
  GripVertical,
  GripHorizontal,
  Maximize,
  Maximize2,
  Minimize,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Expand,
  Shrink,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  Menu,
  Home,
  Settings,
  Sliders,
  SlidersHorizontal,
  LayoutGrid,
  LayoutList,
  LayoutDashboard,
  Layers,
  Layers2,
  Layers3,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Sidebar,
  SidebarOpen,
  SidebarClose,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Bookmark,
  Flag,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Users,
  UsersRound,
  UserCircle,
  UserSquare,
  Contact,
  ContactRound,
  CircleUser,
  Mail,
  MailOpen,
  MailPlus,
  Inbox,
  Send,
  MessageSquare,
  MessageCircle,
  MessagesSquare,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Image,
  ImagePlus,
  ImageMinus,
  Images,
  Camera,
  CameraOff,
  Film,
  Clapperboard,
  Play,
  Pause,
  PlayCircle,
  PauseCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Music,
  Music2,
  Music3,
  Music4,
  Headphones,
  Radio,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,
  FileJson,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  Files,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderInput,
  FolderOutput,
  Archive,
  FileArchive,
  Package,
  Box,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  ListChecks,
  ListTree,
  Quote,
  Code,
  Code2,
  Terminal,
  Braces,
  Hash,
  AtSign,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Pilcrow,
  TextCursor,
  CaseSensitive,
  CaseUpper,
  CaseLower,
  Clock,
  Clock1,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Timer,
  TimerOff,
  TimerReset,
  Hourglass,
  AlarmClock,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarPlus,
  CalendarMinus,
  CalendarClock,
  CalendarRange,
} from "lucide-react";
import type { IconCategory } from "./iconTypes";

export const ICON_CATEGORIES_PART1: IconCategory[] = [
  {
    id: "arrows",
    label: "Arrows",
    icons: [
      { name: "arrow-up", component: ArrowUp, tags: ["up", "direction", "north"] },
      { name: "arrow-down", component: ArrowDown, tags: ["down", "direction", "south"] },
      { name: "arrow-left", component: ArrowLeft, tags: ["left", "direction", "west", "back"] },
      {
        name: "arrow-right",
        component: ArrowRight,
        tags: ["right", "direction", "east", "forward"],
      },
      { name: "arrow-up-right", component: ArrowUpRight, tags: ["diagonal", "northeast"] },
      { name: "arrow-up-left", component: ArrowUpLeft, tags: ["diagonal", "northwest"] },
      { name: "arrow-down-right", component: ArrowDownRight, tags: ["diagonal", "southeast"] },
      { name: "arrow-down-left", component: ArrowDownLeft, tags: ["diagonal", "southwest"] },
      { name: "chevron-up", component: ChevronUp, tags: ["caret", "expand", "collapse"] },
      { name: "chevron-down", component: ChevronDown, tags: ["caret", "expand", "dropdown"] },
      { name: "chevron-left", component: ChevronLeft, tags: ["caret", "back", "previous"] },
      { name: "chevron-right", component: ChevronRight, tags: ["caret", "forward", "next"] },
      { name: "chevrons-up", component: ChevronsUp, tags: ["double", "fast"] },
      { name: "chevrons-down", component: ChevronsDown, tags: ["double", "fast"] },
      { name: "chevrons-left", component: ChevronsLeft, tags: ["double", "fast", "first"] },
      { name: "chevrons-right", component: ChevronsRight, tags: ["double", "fast", "last"] },
      { name: "move-up", component: MoveUp, tags: ["sort", "reorder"] },
      { name: "move-down", component: MoveDown, tags: ["sort", "reorder"] },
      { name: "move-left", component: MoveLeft, tags: ["sort", "reorder"] },
      { name: "move-right", component: MoveRight, tags: ["sort", "reorder"] },
      { name: "corner-up-left", component: CornerUpLeft, tags: ["turn", "reply"] },
      { name: "corner-up-right", component: CornerUpRight, tags: ["turn", "forward"] },
      { name: "corner-down-left", component: CornerDownLeft, tags: ["turn"] },
      { name: "corner-down-right", component: CornerDownRight, tags: ["turn"] },
      { name: "undo", component: Undo2, tags: ["back", "history", "revert"] },
      { name: "redo", component: Redo2, tags: ["forward", "history"] },
      { name: "refresh-cw", component: RefreshCw, tags: ["reload", "sync", "update"] },
      { name: "refresh-ccw", component: RefreshCcw, tags: ["reload", "sync", "update"] },
      { name: "rotate-cw", component: RotateCw, tags: ["clockwise", "turn"] },
      { name: "rotate-ccw", component: RotateCcw, tags: ["counter-clockwise", "turn"] },
    ],
  },
  {
    id: "actions",
    label: "Actions",
    icons: [
      { name: "plus", component: Plus, tags: ["add", "new", "create"] },
      { name: "minus", component: Minus, tags: ["remove", "subtract", "delete"] },
      { name: "x", component: X, tags: ["close", "cancel", "remove", "delete"] },
      { name: "check", component: Check, tags: ["done", "complete", "success", "yes"] },
      { name: "search", component: Search, tags: ["find", "lookup", "magnify"] },
      { name: "edit", component: Edit, tags: ["pencil", "modify", "write"] },
      { name: "edit-2", component: Edit2, tags: ["pencil", "modify", "write"] },
      { name: "edit-3", component: Edit3, tags: ["pencil", "modify", "write"] },
      { name: "trash", component: Trash, tags: ["delete", "remove", "bin"] },
      { name: "trash-2", component: Trash2, tags: ["delete", "remove", "bin"] },
      { name: "copy", component: Copy, tags: ["duplicate", "clone"] },
      { name: "clipboard", component: Clipboard, tags: ["paste", "copy"] },
      { name: "clipboard-copy", component: ClipboardCopy, tags: ["copy"] },
      { name: "clipboard-paste", component: ClipboardPaste, tags: ["paste"] },
      { name: "download", component: Download, tags: ["save", "export", "get"] },
      { name: "upload", component: Upload, tags: ["import", "send", "put"] },
      { name: "save", component: Save, tags: ["disk", "store", "keep"] },
      { name: "share", component: Share, tags: ["send", "social"] },
      { name: "share-2", component: Share2, tags: ["send", "social", "network"] },
      { name: "external-link", component: ExternalLink, tags: ["open", "new-tab", "link"] },
      { name: "more-horizontal", component: MoreHorizontal, tags: ["menu", "options", "dots"] },
      { name: "more-vertical", component: MoreVertical, tags: ["menu", "options", "dots"] },
      { name: "grip", component: Grip, tags: ["drag", "handle", "move"] },
      { name: "grip-vertical", component: GripVertical, tags: ["drag", "handle", "move"] },
      { name: "grip-horizontal", component: GripHorizontal, tags: ["drag", "handle", "move"] },
      { name: "maximize", component: Maximize, tags: ["fullscreen", "expand"] },
      { name: "maximize-2", component: Maximize2, tags: ["fullscreen", "expand"] },
      { name: "minimize", component: Minimize, tags: ["reduce", "shrink"] },
      { name: "minimize-2", component: Minimize2, tags: ["reduce", "shrink"] },
      { name: "zoom-in", component: ZoomIn, tags: ["magnify", "enlarge"] },
      { name: "zoom-out", component: ZoomOut, tags: ["shrink", "reduce"] },
      { name: "expand", component: Expand, tags: ["fullscreen", "grow"] },
      { name: "shrink", component: Shrink, tags: ["reduce", "collapse"] },
      { name: "lock", component: Lock, tags: ["secure", "private", "protected"] },
      { name: "unlock", component: Unlock, tags: ["open", "public", "accessible"] },
      { name: "eye", component: Eye, tags: ["view", "visible", "show"] },
      { name: "eye-off", component: EyeOff, tags: ["hide", "invisible", "hidden"] },
      { name: "filter", component: Filter, tags: ["sort", "funnel", "refine"] },
    ],
  },
  {
    id: "ui",
    label: "Interface",
    icons: [
      { name: "menu", component: Menu, tags: ["hamburger", "navigation", "bars"] },
      { name: "home", component: Home, tags: ["house", "main", "start"] },
      { name: "settings", component: Settings, tags: ["gear", "cog", "preferences"] },
      { name: "sliders", component: Sliders, tags: ["settings", "controls", "adjust"] },
      { name: "sliders-horizontal", component: SlidersHorizontal, tags: ["settings", "controls"] },
      { name: "layout-grid", component: LayoutGrid, tags: ["grid", "tiles", "gallery"] },
      { name: "layout-list", component: LayoutList, tags: ["list", "rows"] },
      { name: "layout-dashboard", component: LayoutDashboard, tags: ["dashboard", "panels"] },
      { name: "layers", component: Layers, tags: ["stack", "levels"] },
      { name: "layers-2", component: Layers2, tags: ["stack", "levels"] },
      { name: "layers-3", component: Layers3, tags: ["stack", "levels"] },
      { name: "panel-left", component: PanelLeft, tags: ["sidebar", "layout"] },
      { name: "panel-right", component: PanelRight, tags: ["sidebar", "layout"] },
      { name: "panel-top", component: PanelTop, tags: ["header", "layout"] },
      { name: "panel-bottom", component: PanelBottom, tags: ["footer", "layout"] },
      { name: "sidebar", component: Sidebar, tags: ["panel", "navigation"] },
      { name: "sidebar-open", component: SidebarOpen, tags: ["panel", "expand"] },
      { name: "sidebar-close", component: SidebarClose, tags: ["panel", "collapse"] },
      { name: "square", component: Square, tags: ["shape", "box", "rectangle"] },
      { name: "circle", component: Circle, tags: ["shape", "round", "dot"] },
      { name: "triangle", component: Triangle, tags: ["shape", "arrow"] },
      { name: "hexagon", component: Hexagon, tags: ["shape", "polygon"] },
      { name: "octagon", component: Octagon, tags: ["shape", "stop"] },
      { name: "pentagon", component: Pentagon, tags: ["shape", "polygon"] },
      { name: "star", component: Star, tags: ["favorite", "rating", "bookmark"] },
      { name: "heart", component: Heart, tags: ["love", "like", "favorite"] },
      { name: "thumbs-up", component: ThumbsUp, tags: ["like", "approve", "good"] },
      { name: "thumbs-down", component: ThumbsDown, tags: ["dislike", "reject", "bad"] },
      { name: "bookmark", component: Bookmark, tags: ["save", "favorite", "flag"] },
      { name: "flag", component: Flag, tags: ["report", "mark", "important"] },
    ],
  },
  {
    id: "users",
    label: "Users",
    icons: [
      { name: "user", component: User, tags: ["person", "profile", "account"] },
      { name: "user-plus", component: UserPlus, tags: ["add", "new", "invite"] },
      { name: "user-minus", component: UserMinus, tags: ["remove", "delete"] },
      { name: "user-check", component: UserCheck, tags: ["verify", "approve"] },
      { name: "user-x", component: UserX, tags: ["remove", "block", "ban"] },
      { name: "users", component: Users, tags: ["people", "team", "group"] },
      { name: "users-round", component: UsersRound, tags: ["people", "team", "group"] },
      { name: "user-circle", component: UserCircle, tags: ["avatar", "profile"] },
      { name: "user-square", component: UserSquare, tags: ["avatar", "profile"] },
      { name: "contact", component: Contact, tags: ["person", "card", "info"] },
      { name: "contact-round", component: ContactRound, tags: ["person", "card"] },
      { name: "circle-user", component: CircleUser, tags: ["avatar", "profile"] },
    ],
  },
  {
    id: "communication",
    label: "Communication",
    icons: [
      { name: "mail", component: Mail, tags: ["email", "envelope", "message"] },
      { name: "mail-open", component: MailOpen, tags: ["email", "read"] },
      { name: "mail-plus", component: MailPlus, tags: ["email", "new", "compose"] },
      { name: "inbox", component: Inbox, tags: ["mail", "messages"] },
      { name: "send", component: Send, tags: ["email", "message", "paper-plane"] },
      { name: "message-square", component: MessageSquare, tags: ["chat", "comment", "bubble"] },
      { name: "message-circle", component: MessageCircle, tags: ["chat", "comment", "bubble"] },
      { name: "messages-square", component: MessagesSquare, tags: ["chat", "conversation"] },
      { name: "phone", component: Phone, tags: ["call", "mobile", "telephone"] },
      { name: "phone-call", component: PhoneCall, tags: ["calling", "ringing"] },
      { name: "phone-incoming", component: PhoneIncoming, tags: ["receive", "answer"] },
      { name: "phone-outgoing", component: PhoneOutgoing, tags: ["dial", "outbound"] },
      { name: "video", component: Video, tags: ["camera", "record", "film"] },
      { name: "video-off", component: VideoOff, tags: ["camera", "disabled"] },
      { name: "mic", component: Mic, tags: ["microphone", "record", "audio"] },
      { name: "mic-off", component: MicOff, tags: ["microphone", "mute", "silent"] },
      { name: "volume", component: Volume, tags: ["sound", "speaker", "audio"] },
      { name: "volume-1", component: Volume1, tags: ["sound", "low"] },
      { name: "volume-2", component: Volume2, tags: ["sound", "high"] },
      { name: "volume-x", component: VolumeX, tags: ["mute", "silent", "off"] },
    ],
  },
  {
    id: "media",
    label: "Media",
    icons: [
      { name: "image", component: Image, tags: ["picture", "photo", "gallery"] },
      { name: "image-plus", component: ImagePlus, tags: ["add", "upload"] },
      { name: "image-minus", component: ImageMinus, tags: ["remove"] },
      { name: "images", component: Images, tags: ["gallery", "photos", "album"] },
      { name: "camera", component: Camera, tags: ["photo", "picture", "capture"] },
      { name: "camera-off", component: CameraOff, tags: ["disabled"] },
      { name: "film", component: Film, tags: ["movie", "video", "reel"] },
      { name: "clapperboard", component: Clapperboard, tags: ["movie", "action", "film"] },
      { name: "play", component: Play, tags: ["start", "video", "audio"] },
      { name: "pause", component: Pause, tags: ["stop", "wait"] },
      { name: "play-circle", component: PlayCircle, tags: ["start", "video"] },
      { name: "pause-circle", component: PauseCircle, tags: ["stop"] },
      { name: "skip-back", component: SkipBack, tags: ["previous", "rewind"] },
      { name: "skip-forward", component: SkipForward, tags: ["next", "fast-forward"] },
      { name: "rewind", component: Rewind, tags: ["back", "previous"] },
      { name: "fast-forward", component: FastForward, tags: ["next", "skip"] },
      { name: "music", component: Music, tags: ["audio", "song", "note"] },
      { name: "music-2", component: Music2, tags: ["audio", "song"] },
      { name: "music-3", component: Music3, tags: ["audio", "song"] },
      { name: "music-4", component: Music4, tags: ["audio", "song"] },
      { name: "headphones", component: Headphones, tags: ["audio", "listen", "music"] },
      { name: "radio", component: Radio, tags: ["broadcast", "audio", "music"] },
    ],
  },
  {
    id: "files",
    label: "Files",
    icons: [
      { name: "file", component: File, tags: ["document", "page"] },
      { name: "file-text", component: FileText, tags: ["document", "text", "doc"] },
      { name: "file-image", component: FileImage, tags: ["photo", "picture"] },
      { name: "file-video", component: FileVideo, tags: ["movie", "media"] },
      { name: "file-audio", component: FileAudio, tags: ["music", "sound"] },
      { name: "file-code", component: FileCode, tags: ["code", "script", "programming"] },
      { name: "file-json", component: FileJson, tags: ["data", "config"] },
      { name: "file-plus", component: FilePlus, tags: ["new", "add", "create"] },
      { name: "file-minus", component: FileMinus, tags: ["remove", "delete"] },
      { name: "file-check", component: FileCheck, tags: ["done", "complete"] },
      { name: "file-x", component: FileX, tags: ["remove", "delete", "cancel"] },
      { name: "files", component: Files, tags: ["documents", "multiple"] },
      { name: "folder", component: Folder, tags: ["directory", "files"] },
      { name: "folder-open", component: FolderOpen, tags: ["directory", "opened"] },
      { name: "folder-plus", component: FolderPlus, tags: ["new", "create"] },
      { name: "folder-minus", component: FolderMinus, tags: ["remove", "delete"] },
      { name: "folder-input", component: FolderInput, tags: ["import", "move"] },
      { name: "folder-output", component: FolderOutput, tags: ["export", "move"] },
      { name: "archive", component: Archive, tags: ["zip", "compress", "storage"] },
      { name: "file-archive", component: FileArchive, tags: ["zip", "compress"] },
      { name: "package", component: Package, tags: ["box", "delivery", "npm"] },
      { name: "box", component: Box, tags: ["package", "container"] },
    ],
  },
  {
    id: "text",
    label: "Text",
    icons: [
      { name: "type", component: Type, tags: ["text", "font", "typography"] },
      { name: "bold", component: Bold, tags: ["text", "format", "strong"] },
      { name: "italic", component: Italic, tags: ["text", "format", "emphasis"] },
      { name: "underline", component: Underline, tags: ["text", "format"] },
      { name: "strikethrough", component: Strikethrough, tags: ["text", "format", "delete"] },
      { name: "align-left", component: AlignLeft, tags: ["text", "format", "paragraph"] },
      { name: "align-center", component: AlignCenter, tags: ["text", "format", "paragraph"] },
      { name: "align-right", component: AlignRight, tags: ["text", "format", "paragraph"] },
      { name: "align-justify", component: AlignJustify, tags: ["text", "format", "paragraph"] },
      { name: "list", component: List, tags: ["bullet", "items"] },
      { name: "list-ordered", component: ListOrdered, tags: ["numbered", "items"] },
      { name: "list-checks", component: ListChecks, tags: ["todo", "checklist"] },
      { name: "list-tree", component: ListTree, tags: ["hierarchy", "nested"] },
      { name: "quote", component: Quote, tags: ["blockquote", "citation"] },
      { name: "code", component: Code, tags: ["programming", "snippet"] },
      { name: "code-2", component: Code2, tags: ["programming", "snippet"] },
      { name: "terminal", component: Terminal, tags: ["console", "command"] },
      { name: "braces", component: Braces, tags: ["code", "json", "object"] },
      { name: "hash", component: Hash, tags: ["number", "tag", "hashtag"] },
      { name: "at-sign", component: AtSign, tags: ["email", "mention"] },
      { name: "heading-1", component: Heading1, tags: ["h1", "title"] },
      { name: "heading-2", component: Heading2, tags: ["h2", "subtitle"] },
      { name: "heading-3", component: Heading3, tags: ["h3"] },
      { name: "heading-4", component: Heading4, tags: ["h4"] },
      { name: "heading-5", component: Heading5, tags: ["h5"] },
      { name: "heading-6", component: Heading6, tags: ["h6"] },
      { name: "pilcrow", component: Pilcrow, tags: ["paragraph", "text"] },
      { name: "text-cursor", component: TextCursor, tags: ["input", "type"] },
      { name: "case-sensitive", component: CaseSensitive, tags: ["text", "match"] },
      { name: "case-upper", component: CaseUpper, tags: ["uppercase", "caps"] },
      { name: "case-lower", component: CaseLower, tags: ["lowercase"] },
    ],
  },
  {
    id: "time",
    label: "Time",
    icons: [
      { name: "clock", component: Clock, tags: ["time", "watch", "hour"] },
      { name: "clock-1", component: Clock1, tags: ["time", "1 oclock"] },
      { name: "clock-2", component: Clock2, tags: ["time", "2 oclock"] },
      { name: "clock-3", component: Clock3, tags: ["time", "3 oclock"] },
      { name: "clock-4", component: Clock4, tags: ["time", "4 oclock"] },
      { name: "clock-5", component: Clock5, tags: ["time", "5 oclock"] },
      { name: "timer", component: Timer, tags: ["stopwatch", "countdown"] },
      { name: "timer-off", component: TimerOff, tags: ["stopwatch", "disabled"] },
      { name: "timer-reset", component: TimerReset, tags: ["stopwatch", "restart"] },
      { name: "hourglass", component: Hourglass, tags: ["time", "wait", "loading"] },
      { name: "alarm-clock", component: AlarmClock, tags: ["wake", "reminder"] },
      { name: "calendar", component: Calendar, tags: ["date", "schedule", "event"] },
      { name: "calendar-days", component: CalendarDays, tags: ["date", "schedule"] },
      { name: "calendar-check", component: CalendarCheck, tags: ["event", "confirmed"] },
      { name: "calendar-plus", component: CalendarPlus, tags: ["add", "new-event"] },
      { name: "calendar-minus", component: CalendarMinus, tags: ["remove", "cancel"] },
      { name: "calendar-clock", component: CalendarClock, tags: ["schedule", "appointment"] },
      { name: "calendar-range", component: CalendarRange, tags: ["date-range", "period"] },
    ],
  },
];
