/**
 * Icon categories 10-17: Shopping, Social, Technology, Alerts, Charts, Design, Security, Location
 *
 * @module constants/iconCategories2
 * @license BSD-3-Clause
 */

import {
  ShoppingCart,
  ShoppingBag,
  Store,
  CreditCard,
  Wallet,
  DollarSign,
  Euro,
  PoundSterling,
  Coins,
  Banknote,
  Receipt,
  Tag,
  Tags,
  Percent,
  BadgePercent,
  Gift,
  Truck,
  Package2,
  Barcode,
  QrCode,
  Globe,
  Globe2,
  Link,
  Link2,
  Unlink,
  Unlink2,
  Rss,
  Podcast,
  Cast,
  Github,
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Chrome,
  Figma,
  Slack,
  Trello,
  Monitor,
  Laptop,
  Laptop2,
  Smartphone,
  Tablet,
  Tv,
  Cpu,
  HardDrive,
  Database,
  Server,
  Cloud as CloudIcon,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Signal,
  Bug,
  TestTube,
  Beaker,
  Zap,
  ZapOff,
  Power,
  PowerOff,
  PlugZap,
  Binary,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitFork,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Bell,
  BellRing,
  BellOff,
  Info,
  HelpCircle,
  CircleHelp,
  BadgeInfo,
  CheckCircle,
  CheckCircle2,
  XCircle,
  XOctagon,
  Loader,
  Loader2,
  LoaderCircle,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  LineChart,
  PieChart,
  AreaChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Gauge,
  Target,
  Crosshair,
  Palette,
  Paintbrush,
  PaintBucket,
  Pipette,
  Eraser,
  Wand2,
  Pen,
  PenTool,
  Pencil,
  Highlighter,
  Brush,
  Sparkles,
  Shapes,
  Component,
  Puzzle,
  Boxes,
  Move,
  Move3d,
  Scaling,
  Crop,
  Focus,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  Key,
  KeyRound,
  Fingerprint,
  Scan,
  ScanFace,
  LockKeyhole,
  UnlockKeyhole,
  MapPin,
  MapPinned,
  Map,
  Navigation,
  Navigation2,
  Compass,
  Building,
  Building2,
  Warehouse,
  Factory,
  Landmark,
  Castle,
  Church,
  Hospital,
} from "lucide-react";
import type { IconCategory } from "./iconTypes";

export const ICON_CATEGORIES_PART2: IconCategory[] = [
  {
    id: "shopping",
    label: "Shopping",
    icons: [
      { name: "shopping-cart", component: ShoppingCart, tags: ["buy", "purchase", "ecommerce"] },
      { name: "shopping-bag", component: ShoppingBag, tags: ["buy", "purchase", "store"] },
      { name: "store", component: Store, tags: ["shop", "retail", "business"] },
      { name: "credit-card", component: CreditCard, tags: ["payment", "buy", "card"] },
      { name: "wallet", component: Wallet, tags: ["money", "payment", "cash"] },
      { name: "dollar-sign", component: DollarSign, tags: ["money", "currency", "usd"] },
      { name: "euro", component: Euro, tags: ["money", "currency", "eur"] },
      { name: "pound-sterling", component: PoundSterling, tags: ["money", "currency", "gbp"] },
      { name: "coins", component: Coins, tags: ["money", "currency", "cash"] },
      { name: "banknote", component: Banknote, tags: ["money", "cash", "bill"] },
      { name: "receipt", component: Receipt, tags: ["invoice", "bill", "transaction"] },
      { name: "tag", component: Tag, tags: ["price", "label", "category"] },
      { name: "tags", component: Tags, tags: ["labels", "categories"] },
      { name: "percent", component: Percent, tags: ["discount", "sale", "off"] },
      { name: "badge-percent", component: BadgePercent, tags: ["discount", "sale"] },
      { name: "gift", component: Gift, tags: ["present", "reward", "bonus"] },
      { name: "truck", component: Truck, tags: ["delivery", "shipping", "transport"] },
      { name: "package-2", component: Package2, tags: ["delivery", "box", "shipment"] },
      { name: "barcode", component: Barcode, tags: ["scan", "product", "upc"] },
      { name: "qr-code", component: QrCode, tags: ["scan", "code", "link"] },
    ],
  },
  {
    id: "social",
    label: "Social",
    icons: [
      { name: "globe", component: Globe, tags: ["world", "internet", "web"] },
      { name: "globe-2", component: Globe2, tags: ["world", "earth"] },
      { name: "link", component: Link, tags: ["url", "chain", "connect"] },
      { name: "link-2", component: Link2, tags: ["url", "chain"] },
      { name: "unlink", component: Unlink, tags: ["disconnect", "break"] },
      { name: "unlink-2", component: Unlink2, tags: ["disconnect", "break"] },
      { name: "rss", component: Rss, tags: ["feed", "blog", "news"] },
      { name: "podcast", component: Podcast, tags: ["audio", "broadcast"] },
      { name: "cast", component: Cast, tags: ["broadcast", "stream", "chromecast"] },
      { name: "github", component: Github, tags: ["code", "git", "repository"] },
      { name: "twitter", component: Twitter, tags: ["social", "tweet", "x"] },
      { name: "facebook", component: Facebook, tags: ["social", "meta"] },
      { name: "instagram", component: Instagram, tags: ["social", "photo"] },
      { name: "linkedin", component: Linkedin, tags: ["social", "professional"] },
      { name: "youtube", component: Youtube, tags: ["video", "social"] },
      { name: "chrome", component: Chrome, tags: ["browser", "google"] },
      { name: "figma", component: Figma, tags: ["design", "tool"] },
      { name: "slack", component: Slack, tags: ["chat", "team", "communication"] },
      { name: "trello", component: Trello, tags: ["project", "board", "tasks"] },
    ],
  },
  {
    id: "tech",
    label: "Technology",
    icons: [
      { name: "monitor", component: Monitor, tags: ["screen", "display", "desktop"] },
      { name: "laptop", component: Laptop, tags: ["computer", "notebook"] },
      { name: "laptop-2", component: Laptop2, tags: ["computer", "notebook"] },
      { name: "smartphone", component: Smartphone, tags: ["phone", "mobile", "device"] },
      { name: "tablet", component: Tablet, tags: ["ipad", "device"] },
      { name: "tv", component: Tv, tags: ["television", "screen", "display"] },
      { name: "cpu", component: Cpu, tags: ["processor", "chip", "hardware"] },
      { name: "hard-drive", component: HardDrive, tags: ["storage", "disk", "data"] },
      { name: "database", component: Database, tags: ["storage", "data", "server"] },
      { name: "server", component: Server, tags: ["hosting", "backend", "computer"] },
      { name: "cloud", component: CloudIcon, tags: ["storage", "hosting", "internet"] },
      { name: "wifi", component: Wifi, tags: ["internet", "wireless", "network"] },
      { name: "wifi-off", component: WifiOff, tags: ["offline", "no-connection"] },
      { name: "bluetooth", component: Bluetooth, tags: ["wireless", "connect"] },
      { name: "bluetooth-off", component: BluetoothOff, tags: ["disabled"] },
      { name: "signal", component: Signal, tags: ["network", "strength", "bars"] },
      { name: "bug", component: Bug, tags: ["error", "debug", "issue"] },
      { name: "test-tube", component: TestTube, tags: ["experiment", "test", "science"] },
      { name: "beaker", component: Beaker, tags: ["experiment", "lab", "science"] },
      { name: "zap", component: Zap, tags: ["lightning", "power", "fast"] },
      { name: "zap-off", component: ZapOff, tags: ["power-off", "disabled"] },
      { name: "power", component: Power, tags: ["on", "start", "button"] },
      { name: "power-off", component: PowerOff, tags: ["shutdown", "off"] },
      { name: "plug-zap", component: PlugZap, tags: ["electric", "power", "charge"] },
      { name: "binary", component: Binary, tags: ["code", "data", "digital"] },
      { name: "git-branch", component: GitBranch, tags: ["version", "code", "fork"] },
      { name: "git-commit", component: GitCommit, tags: ["version", "code", "save"] },
      { name: "git-merge", component: GitMerge, tags: ["version", "code", "combine"] },
      { name: "git-pull-request", component: GitPullRequest, tags: ["version", "code", "pr"] },
      { name: "git-fork", component: GitFork, tags: ["version", "code", "branch"] },
    ],
  },
  {
    id: "alerts",
    label: "Alerts",
    icons: [
      { name: "alert-circle", component: AlertCircle, tags: ["warning", "error", "danger"] },
      { name: "alert-triangle", component: AlertTriangle, tags: ["warning", "caution"] },
      { name: "alert-octagon", component: AlertOctagon, tags: ["error", "stop", "danger"] },
      { name: "bell", component: Bell, tags: ["notification", "alert", "alarm"] },
      { name: "bell-ring", component: BellRing, tags: ["notification", "ringing"] },
      { name: "bell-off", component: BellOff, tags: ["mute", "silent", "disabled"] },
      { name: "info", component: Info, tags: ["information", "help", "about"] },
      { name: "help-circle", component: HelpCircle, tags: ["question", "support", "faq"] },
      { name: "circle-help", component: CircleHelp, tags: ["question", "support"] },
      { name: "badge-info", component: BadgeInfo, tags: ["information", "tooltip"] },
      { name: "check-circle", component: CheckCircle, tags: ["success", "done", "complete"] },
      { name: "check-circle-2", component: CheckCircle2, tags: ["success", "done"] },
      { name: "x-circle", component: XCircle, tags: ["error", "cancel", "close"] },
      { name: "x-octagon", component: XOctagon, tags: ["error", "stop", "block"] },
      { name: "loader", component: Loader, tags: ["loading", "spinner", "wait"] },
      { name: "loader-2", component: Loader2, tags: ["loading", "spinner"] },
      { name: "loader-circle", component: LoaderCircle, tags: ["loading", "spinner"] },
    ],
  },
  {
    id: "charts",
    label: "Charts",
    icons: [
      { name: "bar-chart", component: BarChart, tags: ["graph", "statistics", "data"] },
      { name: "bar-chart-2", component: BarChart2, tags: ["graph", "statistics"] },
      { name: "bar-chart-3", component: BarChart3, tags: ["graph", "horizontal"] },
      { name: "bar-chart-4", component: BarChart4, tags: ["graph", "horizontal"] },
      { name: "line-chart", component: LineChart, tags: ["graph", "trend", "data"] },
      { name: "pie-chart", component: PieChart, tags: ["graph", "statistics", "circle"] },
      { name: "area-chart", component: AreaChart, tags: ["graph", "trend"] },
      { name: "trending-up", component: TrendingUp, tags: ["growth", "increase", "arrow"] },
      { name: "trending-down", component: TrendingDown, tags: ["decline", "decrease"] },
      { name: "activity", component: Activity, tags: ["pulse", "health", "monitor"] },
      { name: "gauge", component: Gauge, tags: ["meter", "speed", "performance"] },
      { name: "target", component: Target, tags: ["goal", "aim", "bullseye"] },
      { name: "crosshair", component: Crosshair, tags: ["aim", "focus", "center"] },
    ],
  },
  {
    id: "design",
    label: "Design",
    icons: [
      { name: "palette", component: Palette, tags: ["color", "art", "theme"] },
      { name: "paintbrush", component: Paintbrush, tags: ["art", "draw", "color"] },
      { name: "paint-bucket", component: PaintBucket, tags: ["fill", "color"] },
      { name: "pipette", component: Pipette, tags: ["color-picker", "eyedropper"] },
      { name: "eraser", component: Eraser, tags: ["delete", "remove", "clear"] },
      { name: "wand-2", component: Wand2, tags: ["magic", "auto", "smart"] },
      { name: "pen", component: Pen, tags: ["draw", "write", "sign"] },
      { name: "pen-tool", component: PenTool, tags: ["bezier", "vector", "path"] },
      { name: "pencil", component: Pencil, tags: ["draw", "write", "edit"] },
      { name: "highlighter", component: Highlighter, tags: ["mark", "annotate"] },
      { name: "brush", component: Brush, tags: ["paint", "art", "draw"] },
      { name: "sparkles", component: Sparkles, tags: ["magic", "new", "ai"] },
      { name: "shapes", component: Shapes, tags: ["geometry", "objects"] },
      { name: "component", component: Component, tags: ["module", "block", "element"] },
      { name: "puzzle", component: Puzzle, tags: ["piece", "plugin", "addon"] },
      { name: "boxes", component: Boxes, tags: ["components", "modules"] },
      { name: "move", component: Move, tags: ["drag", "position", "transform"] },
      { name: "move-3d", component: Move3d, tags: ["3d", "transform", "position"] },
      { name: "scaling", component: Scaling, tags: ["resize", "transform"] },
      { name: "crop", component: Crop, tags: ["resize", "cut", "trim"] },
      { name: "focus", component: Focus, tags: ["center", "target", "aim"] },
    ],
  },
  {
    id: "security",
    label: "Security",
    icons: [
      { name: "shield", component: Shield, tags: ["protect", "security", "safe"] },
      { name: "shield-check", component: ShieldCheck, tags: ["verified", "secure", "safe"] },
      { name: "shield-alert", component: ShieldAlert, tags: ["warning", "danger"] },
      { name: "shield-off", component: ShieldOff, tags: ["unprotected", "vulnerable"] },
      { name: "key", component: Key, tags: ["password", "access", "unlock"] },
      { name: "key-round", component: KeyRound, tags: ["password", "access"] },
      { name: "fingerprint", component: Fingerprint, tags: ["biometric", "identity"] },
      { name: "scan", component: Scan, tags: ["qr", "barcode", "read"] },
      { name: "scan-face", component: ScanFace, tags: ["face-id", "biometric"] },
      { name: "lock-keyhole", component: LockKeyhole, tags: ["secure", "private"] },
      { name: "unlock-keyhole", component: UnlockKeyhole, tags: ["open", "public"] },
    ],
  },
  {
    id: "location",
    label: "Location",
    icons: [
      { name: "map-pin", component: MapPin, tags: ["location", "marker", "place"] },
      { name: "map-pinned", component: MapPinned, tags: ["location", "fixed"] },
      { name: "map", component: Map, tags: ["location", "navigation", "directions"] },
      { name: "navigation", component: Navigation, tags: ["direction", "gps", "arrow"] },
      { name: "navigation-2", component: Navigation2, tags: ["direction", "gps"] },
      { name: "compass", component: Compass, tags: ["direction", "navigation"] },
      { name: "building", component: Building, tags: ["office", "company", "business"] },
      { name: "building-2", component: Building2, tags: ["office", "skyscraper"] },
      { name: "warehouse", component: Warehouse, tags: ["storage", "inventory"] },
      { name: "factory", component: Factory, tags: ["manufacturing", "industry"] },
      { name: "landmark", component: Landmark, tags: ["bank", "government", "building"] },
      { name: "castle", component: Castle, tags: ["fortress", "medieval"] },
      { name: "church", component: Church, tags: ["religion", "chapel"] },
      { name: "hospital", component: Hospital, tags: ["medical", "health", "emergency"] },
    ],
  },
];
