/**
 * Media Tab UI Types
 * @license BSD-3-Clause
 */

import type * as React from "react";
import type {
  StockPhoto,
  StockVideo,
  DiscIcon,
  DiscFont,
} from "../../../../../engine/media/MediaManager";
import type { MediaSortBy, SortDirection, UploadProgress } from "../../../../../shared/types/media";
import type { MediaAsset } from "../../../../../shared/types/media";

export type { MediaSortBy, SortDirection, UploadProgress, MediaAsset };
export type { StockPhoto, StockVideo, DiscIcon, DiscFont };

// --- Nav ---

export type MediaSource = "mine" | "disc";
export type MediaTypeFilter = "all" | "img" | "vid" | "ico" | "fnt";

export interface MediaFolder {
  id: string;
  name: string;
  parentId: string | null;
  createdAt: string;
  updatedAt: string;
}

// --- Library ---

/** Count per type — shown in TypePill badges */
export interface TypeCounts {
  all: number;
  img: number;
  vid: number;
  ico: number;
  fnt: number;
}

/** A library item (maps MediaAsset to display-ready shape) */
export interface LibraryItem {
  key: string;
  name: string;
  type: "img" | "vid" | "ico" | "fnt";
  src: string;
  thumb?: string;
  size: number; // bytes
  duration?: number; // seconds, video only
  width?: number;
  height?: number;
  altText?: string;
  /**
   * P7 — provenance for AI-generated alt text. When present, the panel
   * shows "AI-generated by {model} on {date}" + a Regenerate button.
   */
  generatedAltMeta?: {
    generatedAt: string;
    model: string;
  };
  createdAt: string;
  mimeType: string;
  assetSource?: "uploaded" | "stock" | "ai";
}

// --- Delete confirmation ---

export interface ConfirmDeletePayload {
  keys: string[];
  names: string[];
  inUseCount: number;
  isBulk: boolean;
}

// --- Upload failure tracking ---

export interface FailedUpload {
  fileName: string;
  reason: string;
}

// --- Overlays ---

export interface CtxMenuState {
  x: number;
  y: number;
  item: LibraryItem;
}

// --- Sub-hook result interfaces ---

export interface LibraryStateResult {
  rawAssets: MediaAsset[];
  libraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;
  createFolder(name: string): Promise<void>;
  inspectFolder(id: string): { assetCount: number; subFolderCount: number };
  deleteFolder(id: string, options?: { force?: boolean }): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  activeType: MediaTypeFilter;
  librarySearch: string;
  setLibrarySearch(q: string): void;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  setActiveType(t: MediaTypeFilter): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;
}

export interface UploadStateResult {
  uploadQueue: UploadProgress[];
  failedUploads: FailedUpload[];
  storageUsed: number;
  /** Phase C: total quota bytes. From server when available, else local IndexedDB cap. */
  storageTotal: number;
  panelDragOver: boolean;
  upload(files: File[], opts?: { folderId?: string | null }): void;
  dismissFailedUploads(): void;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;
}

export interface SelectionStateResult {
  selMode: boolean;
  selectedKeys: Set<string>;
  confirmDelete: ConfirmDeletePayload | null;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
}

export type DiscSource = "unsplash" | "pexels" | "pixabay";

export interface DiscoveryStateResult {
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSource: DiscSource;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  setDiscSource(s: DiscSource): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  saveToLibrary(type: "img" | "vid", item: StockPhoto | StockVideo): Promise<void>;
}

// --- Full state result (returned by useMediaState) ---

export interface MediaStateResult {
  // Navigation
  activeType: MediaTypeFilter;
  setType(t: MediaTypeFilter): void;
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;

  // Library
  libraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  createFolder(name: string): Promise<void>;
  deleteFolder(id: string): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  uploadQueue: UploadProgress[];
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  upload(files: File[], opts?: { folderId?: string | null }): void;
  failedUploads: FailedUpload[];
  dismissFailedUploads(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
  confirmDelete: ConfirmDeletePayload | null;
  insertToCanvas(key: string): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;

  // Discovery
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  saveToLibrary(type: "img" | "vid", item: StockPhoto | StockVideo): Promise<void>;

  // Panel drag
  panelDragOver: boolean;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;

  // Shared
  librarySearch: string;
  setLibrarySearch(q: string): void;
  storage: { used: number; total: number };

  // Clipboard
  copyUrl(item: LibraryItem): void;

  // Overlays
  ctxMenu: CtxMenuState | null;
  openCtxMenu(e: React.MouseEvent, item: LibraryItem): void;
  closeCtxMenu(): void;
  detailItem: LibraryItem | null;
  openDetail(item: LibraryItem): void;
  closeDetail(): void;

  // Selection context (canvas → media replace flow)
  selectionContext: { elementId: string; label?: string } | null;
  setSelectionContext(ctx: { elementId: string; label?: string } | null): void;

  // §12 expanded-panel mode (320 ↔ 560)
  panelExpanded: boolean;
  setPanelExpanded(v: boolean): void;

  // §21 replace-across pair (old + new srcs flow into ReplaceAcrossDialog)
  replaceAcrossPair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null;
  setReplaceAcrossPair(
    pair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null
  ): void;

  // §10/§15 usage tracking — Map<assetKey, distinct-page-count> driving UsagePips
  // on AssetCell + 'Where used' tab on detail drawer.
  usageMap: Map<string, number>;
}

// --- Prop slices ---

export interface TypePillsProps {
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  discMode: boolean;
  onTypeChange(t: MediaTypeFilter): void;
}

export interface LibraryViewProps {
  items: LibraryItem[];
  uploadQueue: UploadProgress[];
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  searchQuery: string;
  onSort(by: MediaSortBy, dir: SortDirection): void;
  onGridN(n: 2 | 3 | 4): void;
  onFmt(f: string): void;
  onSelToggle(): void;
  onSelect(key: string): void;
  onSelectAll(): void;
  onRequestBulkDelete(items: LibraryItem[]): void;
  onRequestDelete(key: string): void;
  onInsert(key: string): void;
  onCtxMenu(e: React.MouseEvent, item: LibraryItem): void;
  onDetail(item: LibraryItem): void;
}

export type DiscOrientation = "all" | "landscape" | "portrait" | "squarish";
export type DiscColor =
  | "all"
  | "black_and_white"
  | "black"
  | "white"
  | "yellow"
  | "orange"
  | "red"
  | "purple"
  | "magenta"
  | "green"
  | "teal"
  | "blue";

export interface DiscoveryViewProps {
  activeType: MediaTypeFilter;
  photos: StockPhoto[];
  videos: StockVideo[];
  icons: DiscIcon[];
  fonts: DiscFont[];
  loading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  searchQuery: string;
  orientation: DiscOrientation;
  color: DiscColor;
  /** S19: current source provider (Unsplash / Pexels / Pixabay). */
  source?: DiscSource;
  /** S19: monthly stock-search quota strip; hidden when omitted. */
  quota?: { used: number; limit: number; upgradeHref?: string };
  onSearch(q: string, orientation?: DiscOrientation, color?: DiscColor): void;
  onSetOrientation(o: DiscOrientation): void;
  onSetColor(c: DiscColor): void;
  /** S19: switch the active stock provider; triggers a re-search. */
  onSetSource?(s: DiscSource): void;
  onLoadMore(type: "img" | "vid"): void;
  onSave(type: "img" | "vid", item: StockPhoto | StockVideo): void;
  onInsert(filename: string): void;
}

export interface UploadZoneProps {
  storage: { used: number; total: number };
  onUpload(files: File[]): void;
  disabled?: boolean;
  /** Currently-uploading files; reserved for future queue UI. Accepted but unused today. */
  uploadQueue?: UploadProgress[];
}
