/**
 * Media Tab UI Types
 * @license BSD-3-Clause
 */

import type * as React from "react";
import type {
  StockPhoto,
  StockVideo,
  DiscIcon,
  DiscFont,
} from "../../../../../engine/media/MediaManager";
import type { MediaSortBy, SortDirection, UploadProgress, UploadResult } from "../../../../../shared/types/media";
import type { MediaAsset } from "../../../../../shared/types/media";
import type { StockFailureReason } from "../../../../../services/stock/StockService";

export type { MediaSortBy, SortDirection, UploadProgress, MediaAsset };
export type { StockFailureReason };
export type { StockPhoto, StockVideo, DiscIcon, DiscFont };

// --- Nav ---

export type MediaSource = "mine" | "disc";
export type MediaTypeFilter = "all" | "img" | "vid" | "ico" | "fnt";
/** One selectable pill — the board's multi-select filter has no "all" member. */
export type MediaBucket = Exclude<MediaTypeFilter, "all">;

export interface MediaFolder {
  id: string;
  name: string;
  parentId: string | null;
  createdAt: string;
  updatedAt: string;
}

// --- Library ---

/** Count per type — shown in TypePill badges */
export interface TypeCounts {
  all: number;
  img: number;
  vid: number;
  ico: number;
  fnt: number;
}

/** A library item (maps MediaAsset to display-ready shape) */
export interface LibraryItem {
  key: string;
  name: string;
  /** Label with the file extension restored — board 144:2 draws full filenames. */
  displayName?: string;
  type: "img" | "vid" | "ico" | "fnt";
  src: string;
  thumb?: string;
  /** The folder the asset is filed in; null at the root ("unfiled"). The
   *  Move modal (Clone 3683:19950) says where each checked file IS, and the
   *  move result (3699:20381) tells a file that moved from one that was
   *  already there — both read this. */
  folderId?: string | null;
  size: number; // bytes
  duration?: number; // seconds, video only
  width?: number;
  height?: number;
  altText?: string;
  /** True when the asset lives in this browser's IndexedDB and never reached
   *  the server — its src is a session Object URL, so it will not render on a
   *  published page. `MediaManager` persists it and rebuilds the retry queue
   *  from it. The library's sync pill reads this; before 2026-08-25 that pill
   *  was a hardcoded string that could not tell the two cases apart. */
  localOnly?: boolean;
  /**
   * P7 — provenance for AI-generated alt text. When present, the panel
   * shows "AI-generated by {model} on {date}" + a Regenerate button.
   */
  generatedAltMeta?: {
    generatedAt: string;
    model: string;
  };
  createdAt: string;
  mimeType: string;
  assetSource?: "uploaded" | "stock" | "ai";
  /**
   * Dashboard MediaAsset id (the synced server row). Present once the asset
   * has been uploaded + synced; absent for local-only / stock items. Used to
   * read & write the server-side version history (media.{list,create,restore}
   * AssetVersion) from the detail drawer's Versions tab.
   */
  assetId?: string;
  /** The file's tags — the rail's TAGS chips (Clone 3695:45155) and the tag
   *  filter (3721:43697) read them; the rail's TAGS block writes them. */
  tags?: string[];
  /** A font file ADDED as a site font (Clone 3686:42317) — the rail's meta
   *  line reads it (`Site font · added` / `Uploaded · not added`). Written
   *  by the Site fonts dialog only, through the engine. */
  siteFont?: boolean;
}

// --- Delete confirmation ---

/** One asset the delete would break, and where it is used. */
export interface AssetUsage {
  /** Library key — the confirm joins each checked file to its count by it. */
  key: string;
  name: string;
  /** Elements on the site referencing it — the Clone's "Used in 3 site
   *  placements" (3708:20650) and "hero-dark.jpg (3 uses)" (3701:20385). The
   *  same `findByMediaSrc` answer the rail's USED IN and the grid's `used ×3`
   *  print, so the three never disagree. */
  count: number;
  /** Page names holding an element that references it. Empty when the element
   *  cannot be traced to a page — named as unknown rather than dropped. */
  pages: string[];
}

export interface ConfirmDeletePayload {
  keys: string[];
  names: string[];
  inUseCount: number;
  /* The count alone told a user that something would break and not what. With
     one usage you can guess; with nine you cannot act on the warning you were
     given, so the warning stops being a warning. */
  inUse: AssetUsage[];
  isBulk: boolean;
}

// --- Upload failure tracking ---

export interface FailedUpload {
  fileName: string;
  reason: string;
  /** The refused file's bytes — present when the engine's size gate said no. */
  size?: number;
  /** The bytes its type may have (Clone 3584:45522 → 3585:23326: the
   *  rejected row offers a replacement against exactly this). */
  limit?: number;
}

// --- Overlays ---

export interface CtxMenuState {
  x: number;
  y: number;
  item: LibraryItem;
}

// --- Sub-hook result interfaces ---

export interface LibraryStateResult {
  /**
   * How far the server pull got: the cursor for the next page (null when the
   * library is fully on screen) and how many assets exist in total. Null until
   * the first page lands — or forever in the standalone demo, which has no
   * server to page.
   */
  serverPage: { nextCursor: string | null; total: number; loaded: number } | null;
  /**
   * Where a whole-library search stands. `truncated` means the SEARCH itself
   * was paged and only its first page is in hand; `failed` means the server leg
   * did not come back, which must never be shown as "no match".
   */
  searchState: "idle" | "searching" | "whole" | "truncated" | "failed";
  loadingMore: boolean;
  /** The last "Load more" did not come back. Offered as a retry, not a toast. */
  loadMoreError: boolean;
  loadMoreAssets(): Promise<void>;
  /** False only once storage has been read — see useLibraryState. */
  libraryLoading: boolean;
  /** Non-null when storage could not be read at all. NOT the same as empty. */
  libraryError: string | null;
  retryLibraryLoad(): void;
  rawAssets: MediaAsset[];
  /** The scoped, filtered, sorted list the grid draws. */
  libraryItems: LibraryItem[];
  /** Every asset, unscoped — the SMART rows count the library, not a folder. */
  allLibraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  /** Direct-child asset count per folder id; a folder with none is absent. */
  folderCounts: ReadonlyMap<string, number>;
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;
  /** Files `name` under the current folder; resolves with the folder made. */
  createFolder(name: string): Promise<MediaFolder>;
  inspectFolder(id: string): { assetCount: number; subFolderCount: number };
  deleteFolder(id: string, options?: { force?: boolean }): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  activeType: MediaTypeFilter;
  activeTypes: ReadonlySet<MediaBucket>;
  librarySearch: string;
  setLibrarySearch(q: string): void;
  /** Clone 3721:43697 — the TAGS chip's filter: a tag, or null for none.
   *  Applied after the scope and before the search; the scope stays. */
  tagFilter: string | null;
  setTagFilter(tag: string | null): void;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  setActiveType(t: MediaTypeFilter): void;
  toggleType(t: MediaBucket): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;
}

export interface UploadStateResult {
  uploadQueue: UploadProgress[];
  failedUploads: FailedUpload[];
  storageUsed: number;
  /** Phase C: total quota bytes. From server when available, else local IndexedDB cap. */
  storageTotal: number;
  panelDragOver: boolean;
  /** Resolves the engine's result per file, in order — the asset that landed
   *  or the reason it did not. Clone 3724:20832 (Upload complete) and
   *  3585:23337 (Replacement uploaded) both read what landed. */
  upload(files: File[], opts?: { folderId?: string | null }): Promise<UploadResult[]>;
  retryUpload(fileName: string): void;
  /** Board 1163:13948 — drop a failed upload row (queue and failure record). */
  dismissUpload(fileName: string): void;
  dismissFailedUploads(): void;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;
}

export interface SelectionStateResult {
  selMode: boolean;
  selectedKeys: Set<string>;
  confirmDelete: ConfirmDeletePayload | null;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
  /** §14 — shift-click range select. Anchored on last toggleSelect. */
  shiftSelect(key: string): void;
  /** §14 — right-click "Select" entry: enter mode + pre-select one item. */
  enterSelectModeWith(key: string): void;
  /** Which of these assets are on a page, and which pages. The delete confirm
   *  and the details rail's USED IN (Clone 3695:20340 — "1 place — Menu
   *  preview") read the same answer. */
  checkInUse(keys: string[]): AssetUsage[];
  /** Empty the checked set without leaving select mode (the bulk bar's ✕ Clear). */
  clearSelection(): void;
}

export type DiscSource = "unsplash" | "pexels" | "pixabay";

export interface DiscoveryStateResult {
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  /** WHY the last search failed, or null when it did not. A reason and an
      empty result are different facts — the modal used to render both as
      "No photos found for …" (blocker A-STOCK). Truthy on any failure, so
      callers that only care whether it broke can still just test it. */
  searchFailed: StockFailureReason | null;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSource: DiscSource;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  setDiscSource(s: DiscSource): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  /** Resolves with the asset the library now holds (Clone 3695:45573 names it and
      View asset selects it), null when the engine refused. Icons save too —
      their SVG data URL goes through the same upload gate. */
  saveToLibrary(type: "img" | "vid" | "ico", item: StockPhoto | StockVideo | DiscIcon): Promise<{ key: string; name: string } | null>;
}

// --- Full state result (returned by useMediaState) ---

export interface MediaStateResult {
  /** See `LibraryStateResult` — forwarded so the drawer can say how much of the
   *  server library it is showing. */
  serverPage: { nextCursor: string | null; total: number; loaded: number } | null;
  searchState: "idle" | "searching" | "whole" | "truncated" | "failed";
  loadingMore: boolean;
  loadMoreError: boolean;
  loadMoreAssets(): Promise<void>;
  /** False only once storage has been read — see useLibraryState. */
  libraryLoading: boolean;
  /** Non-null when storage could not be read at all. NOT the same as empty. */
  libraryError: string | null;
  retryLibraryLoad(): void;
  // Navigation
  activeType: MediaTypeFilter;
  activeTypes: ReadonlySet<MediaBucket>;
  setType(t: MediaTypeFilter): void;
  toggleType(t: MediaBucket): void;
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;

  // Library
  libraryItems: LibraryItem[];
  /** See `LibraryStateResult.allLibraryItems`. */
  allLibraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  /** See `LibraryStateResult.folderCounts`. */
  folderCounts: ReadonlyMap<string, number>;
  /** Files `name` under the current folder; resolves with the folder made. */
  createFolder(name: string): Promise<MediaFolder>;
  inspectFolder(id: string): { assetCount: number; subFolderCount: number };
  deleteFolder(id: string, options?: { force?: boolean }): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  uploadQueue: UploadProgress[];
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  shiftSelect(key: string): void;
  enterSelectModeWith(key: string): void;
  checkInUse(keys: string[]): AssetUsage[];
  /** Empty the checked set without leaving select mode (the bulk bar's ✕ Clear). */
  clearSelection(): void;
  /** See `UploadStateResult.upload` — the engine's result per file. */
  upload(files: File[], opts?: { folderId?: string | null }): Promise<UploadResult[]>;
  retryUpload(fileName: string): void;
  /** Board 1163:13948 — drop a failed upload row (queue and failure record). */
  dismissUpload(fileName: string): void;
  failedUploads: FailedUpload[];
  dismissFailedUploads(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
  confirmDelete: ConfirmDeletePayload | null;
  insertToCanvas(key: string): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;

  // Discovery
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  /** WHY the last search failed, or null when it did not. A reason and an
      empty result are different facts — the modal used to render both as
      "No photos found for …" (blocker A-STOCK). Truthy on any failure, so
      callers that only care whether it broke can still just test it. */
  searchFailed: StockFailureReason | null;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  saveToLibrary: DiscoveryStateResult["saveToLibrary"];

  // Panel drag
  panelDragOver: boolean;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;

  // Shared
  librarySearch: string;
  setLibrarySearch(q: string): void;
  /** Library-only search — the fullpage Asset library's field (Clone
   *  3695:44339, "Search across all folders…"). `setLibrarySearch` is the
   *  drawer's unified search and also fires stock discovery, which toasts
   *  "Stock search isn't set up" on every third keystroke when no provider
   *  key is configured. */
  setLibraryQuery(q: string): void;
  /** See `LibraryStateResult.tagFilter`. */
  tagFilter: string | null;
  setTagFilter(tag: string | null): void;
  storage: { used: number; total: number };

  // Clipboard
  copyUrl(item: LibraryItem): void;

  // Overlays
  ctxMenu: CtxMenuState | null;
  /** Opens the asset menu at the pointer, or at `anchor` when a control (the
   *  card's `···`, Clone 3721:43552) rather than a right-click opened it. */
  openCtxMenu(e: React.MouseEvent, item: LibraryItem, anchor?: { x: number; y: number }): void;
  closeCtxMenu(): void;
  detailItem: LibraryItem | null;
  openDetail(item: LibraryItem): void;
  closeDetail(): void;

  // Selection context (canvas → media replace flow)
  selectionContext: { elementId: string; label?: string } | null;
  setSelectionContext(ctx: { elementId: string; label?: string } | null): void;

  // §12 expanded-panel mode (320 ↔ 560)
  panelExpanded: boolean;
  setPanelExpanded(v: boolean): void;

  // §21 replace-across pair (old + new srcs flow into ReplaceAcrossDialog)
  replaceAcrossPair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null;
  setReplaceAcrossPair(
    pair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null
  ): void;

  // §10/§15 usage tracking — Map<assetKey, distinct-page-count> driving UsagePips
  // on AssetCell + 'Where used' tab on detail drawer.
  usageMap: Map<string, number>;
}

// --- Prop slices ---

export interface TypePillsProps {
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  discMode: boolean;
  onTypeChange(t: MediaTypeFilter): void;
}

export interface LibraryViewProps {
  items: LibraryItem[];
  uploadQueue: UploadProgress[];
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  searchQuery: string;
  /** All folders flat — for §14 Move-to-folder picker. */
  allFolders: MediaFolder[];
  onSort(by: MediaSortBy, dir: SortDirection): void;
  onGridN(n: 2 | 3 | 4): void;
  onFmt(f: string): void;
  onSelToggle(): void;
  onSelect(key: string): void;
  /** §14 — shift-click range select. Anchored on previous toggleSelect. */
  onShiftSelect(key: string): void;
  onSelectAll(): void;
  onRequestBulkDelete(items: LibraryItem[]): void;
  onRequestDelete(key: string): void;
  onInsert(key: string): void;
  onCtxMenu(e: React.MouseEvent, item: LibraryItem): void;
  onDetail(item: LibraryItem): void;
  /** §14 — bulk move selected assets into a folder. null = root. */
  onMoveSelected(folderId: string | null): void;
}

export type DiscOrientation = "all" | "landscape" | "portrait" | "squarish";
export type DiscColor =
  | "all"
  | "black_and_white"
  | "black"
  | "white"
  | "yellow"
  | "orange"
  | "red"
  | "purple"
  | "magenta"
  | "green"
  | "teal"
  | "blue";

export interface UploadZoneProps {
  /** Lets a caller (the drawer footer's Upload link) open this zone's file dialog. */
  inputRef?: React.RefObject<HTMLInputElement | null>;
  /** Drawer mode (board 144:2): no drop box at rest — see UploadZone's own note. */
  compact?: boolean;
  storage: { used: number; total: number };
  onUpload(files: File[]): void;
  disabled?: boolean;
  /** Currently-uploading files. When any item has status "uploading"/"optimizing"/"processing",
   *  the zone applies med-upload-zone--uploading. Failed items render below the zone. */
  uploadQueue?: UploadProgress[];
  /** The engine's verdicts by file name — a failed row whose record carries
   *  a `limit` was the size gate, and its door is a replacement, not Retry
   *  (Clone 3584:45522). */
  failedUploads?: FailedUpload[];
  /** §22 — fired when user clicks Retry on a failed queue item. */
  onRetryUpload?(fileName: string): void;
  /** `Choose a smaller file…` picked one: the refused record and the pick. */
  onReplacementPicked?(original: FailedUpload, file: File): void;
  /** Quota-warn band's "Optimise images to free space ›" (board 145:199). */
  onOptimize?(): void;
}
