/**
 * Media Tab UI Types
 * @license BSD-3-Clause
 */

import type * as React from "react";
import type {
  StockPhoto,
  StockVideo,
  DiscIcon,
  DiscFont,
} from "../../../../../engine/media/MediaManager";
import type { MediaSortBy, SortDirection, UploadProgress } from "../../../../../shared/types/media";
import type { MediaAsset } from "../../../../../shared/types/media";

export type { MediaSortBy, SortDirection, UploadProgress, MediaAsset };
export type { StockPhoto, StockVideo, DiscIcon, DiscFont };

// --- Nav ---

export type MediaSource = "mine" | "disc";
export type MediaTypeFilter = "all" | "img" | "vid" | "ico" | "fnt";
/** One selectable pill — the board's multi-select filter has no "all" member. */
export type MediaBucket = Exclude<MediaTypeFilter, "all">;

export interface MediaFolder {
  id: string;
  name: string;
  parentId: string | null;
  createdAt: string;
  updatedAt: string;
}

// --- Library ---

/** Count per type — shown in TypePill badges */
export interface TypeCounts {
  all: number;
  img: number;
  vid: number;
  ico: number;
  fnt: number;
}

/** A library item (maps MediaAsset to display-ready shape) */
export interface LibraryItem {
  key: string;
  name: string;
  /** Label with the file extension restored — board 144:2 draws full filenames. */
  displayName?: string;
  type: "img" | "vid" | "ico" | "fnt";
  src: string;
  thumb?: string;
  size: number; // bytes
  duration?: number; // seconds, video only
  width?: number;
  height?: number;
  altText?: string;
  /**
   * P7 — provenance for AI-generated alt text. When present, the panel
   * shows "AI-generated by {model} on {date}" + a Regenerate button.
   */
  generatedAltMeta?: {
    generatedAt: string;
    model: string;
  };
  createdAt: string;
  mimeType: string;
  assetSource?: "uploaded" | "stock" | "ai";
  /**
   * Dashboard MediaAsset id (the synced server row). Present once the asset
   * has been uploaded + synced; absent for local-only / stock items. Used to
   * read & write the server-side version history (media.{list,create,restore}
   * AssetVersion) from the detail drawer's Versions tab.
   */
  assetId?: string;
}

// --- Delete confirmation ---

export interface ConfirmDeletePayload {
  keys: string[];
  names: string[];
  inUseCount: number;
  isBulk: boolean;
}

// --- Upload failure tracking ---

export interface FailedUpload {
  fileName: string;
  reason: string;
}

// --- Overlays ---

export interface CtxMenuState {
  x: number;
  y: number;
  item: LibraryItem;
}

// --- Sub-hook result interfaces ---

export interface LibraryStateResult {
  /**
   * How far the server pull got: the cursor for the next page (null when the
   * library is fully on screen) and how many assets exist in total. Null until
   * the first page lands — or forever in the standalone demo, which has no
   * server to page.
   */
  serverPage: { nextCursor: string | null; total: number; loaded: number } | null;
  /**
   * Where a whole-library search stands. `truncated` means the SEARCH itself
   * was paged and only its first page is in hand; `failed` means the server leg
   * did not come back, which must never be shown as "no match".
   */
  searchState: "idle" | "searching" | "whole" | "truncated" | "failed";
  loadingMore: boolean;
  /** The last "Load more" did not come back. Offered as a retry, not a toast. */
  loadMoreError: boolean;
  loadMoreAssets(): Promise<void>;
  /** False only once storage has been read — see useLibraryState. */
  libraryLoading: boolean;
  /** Non-null when storage could not be read at all. NOT the same as empty. */
  libraryError: string | null;
  retryLibraryLoad(): void;
  rawAssets: MediaAsset[];
  libraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;
  createFolder(name: string): Promise<void>;
  inspectFolder(id: string): { assetCount: number; subFolderCount: number };
  deleteFolder(id: string, options?: { force?: boolean }): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  activeType: MediaTypeFilter;
  activeTypes: ReadonlySet<MediaBucket>;
  librarySearch: string;
  setLibrarySearch(q: string): void;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  setActiveType(t: MediaTypeFilter): void;
  toggleType(t: MediaBucket): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;
}

export interface UploadStateResult {
  uploadQueue: UploadProgress[];
  failedUploads: FailedUpload[];
  storageUsed: number;
  /** Phase C: total quota bytes. From server when available, else local IndexedDB cap. */
  storageTotal: number;
  panelDragOver: boolean;
  upload(files: File[], opts?: { folderId?: string | null }): Promise<boolean>;
  retryUpload(fileName: string): void;
  /** Board 1163:13948 — drop a failed upload row. */
  dismissUpload(fileName: string): void;
  dismissFailedUploads(): void;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;
}

export interface SelectionStateResult {
  selMode: boolean;
  selectedKeys: Set<string>;
  confirmDelete: ConfirmDeletePayload | null;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
  /** §14 — shift-click range select. Anchored on last toggleSelect. */
  shiftSelect(key: string): void;
  /** §14 — right-click "Select" entry: enter mode + pre-select one item. */
  enterSelectModeWith(key: string): void;
}

export type DiscSource = "unsplash" | "pexels" | "pixabay";

export interface DiscoveryStateResult {
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSource: DiscSource;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  setDiscSource(s: DiscSource): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  saveToLibrary(type: "img" | "vid", item: StockPhoto | StockVideo): Promise<void>;
}

// --- Full state result (returned by useMediaState) ---

export interface MediaStateResult {
  /** See `LibraryStateResult` — forwarded so the drawer can say how much of the
   *  server library it is showing. */
  serverPage: { nextCursor: string | null; total: number; loaded: number } | null;
  searchState: "idle" | "searching" | "whole" | "truncated" | "failed";
  loadingMore: boolean;
  loadMoreError: boolean;
  loadMoreAssets(): Promise<void>;
  /** False only once storage has been read — see useLibraryState. */
  libraryLoading: boolean;
  /** Non-null when storage could not be read at all. NOT the same as empty. */
  libraryError: string | null;
  retryLibraryLoad(): void;
  // Navigation
  activeType: MediaTypeFilter;
  activeTypes: ReadonlySet<MediaBucket>;
  setType(t: MediaTypeFilter): void;
  toggleType(t: MediaBucket): void;
  currentFolderId: string | null;
  setCurrentFolderId(id: string | null): void;

  // Library
  libraryItems: LibraryItem[];
  folders: MediaFolder[];
  allFolders: MediaFolder[];
  createFolder(name: string): Promise<void>;
  inspectFolder(id: string): { assetCount: number; subFolderCount: number };
  deleteFolder(id: string, options?: { force?: boolean }): Promise<void>;
  moveAsset(assetId: string, folderId: string | null): Promise<void>;
  bulkMoveAssets(assetIds: string[], folderId: string | null): Promise<void>;
  uploadQueue: UploadProgress[];
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  setSort(by: MediaSortBy, dir: SortDirection): void;
  setGridN(n: 2 | 3 | 4): void;
  setFmtFilter(f: string): void;
  toggleSelMode(): void;
  toggleSelect(key: string): void;
  selectAll(): void;
  shiftSelect(key: string): void;
  enterSelectModeWith(key: string): void;
  upload(files: File[], opts?: { folderId?: string | null }): Promise<boolean>;
  retryUpload(fileName: string): void;
  /** Board 1163:13948 — drop a failed upload row. */
  dismissUpload(fileName: string): void;
  failedUploads: FailedUpload[];
  dismissFailedUploads(): void;
  requestDelete(key: string): void;
  requestBulkDelete(items: LibraryItem[]): void;
  executeDelete(): Promise<void>;
  cancelDelete(): void;
  confirmDelete: ConfirmDeletePayload | null;
  insertToCanvas(key: string): void;
  renameItem(key: string, name: string): Promise<void>;
  renameFolder(id: string, name: string): Promise<void>;
  updateItem(key: string, updates: Partial<LibraryItem>): Promise<void>;

  // Discovery
  stockPhotos: StockPhoto[];
  stockVideos: StockVideo[];
  discIcons: DiscIcon[];
  discFonts: DiscFont[];
  discLoading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  discoverySearch: string;
  isDiscoveryEmpty: boolean;
  discOrientation: DiscOrientation;
  discColor: DiscColor;
  discSearchAll(query: string, orientation?: DiscOrientation, color?: DiscColor): void;
  setDiscOrientation(o: DiscOrientation): void;
  setDiscColor(c: DiscColor): void;
  loadMoreDisc(type: "img" | "vid"): Promise<void>;
  saveToLibrary(type: "img" | "vid", item: StockPhoto | StockVideo): Promise<void>;

  // Panel drag
  panelDragOver: boolean;
  handlePanelDragEnter(e: React.DragEvent): void;
  handlePanelDragLeave(e: React.DragEvent): void;
  handlePanelDragOver(e: React.DragEvent): void;
  handlePanelDrop(e: React.DragEvent): void;

  // Shared
  librarySearch: string;
  setLibrarySearch(q: string): void;
  storage: { used: number; total: number };

  // Clipboard
  copyUrl(item: LibraryItem): void;

  // Overlays
  ctxMenu: CtxMenuState | null;
  openCtxMenu(e: React.MouseEvent, item: LibraryItem): void;
  closeCtxMenu(): void;
  detailItem: LibraryItem | null;
  openDetail(item: LibraryItem): void;
  closeDetail(): void;

  // Selection context (canvas → media replace flow)
  selectionContext: { elementId: string; label?: string } | null;
  setSelectionContext(ctx: { elementId: string; label?: string } | null): void;

  // §12 expanded-panel mode (320 ↔ 560)
  panelExpanded: boolean;
  setPanelExpanded(v: boolean): void;

  // §21 replace-across pair (old + new srcs flow into ReplaceAcrossDialog)
  replaceAcrossPair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null;
  setReplaceAcrossPair(
    pair: { oldSrc: string; newSrc: string; oldLabel: string; newLabel: string } | null
  ): void;

  // §10/§15 usage tracking — Map<assetKey, distinct-page-count> driving UsagePips
  // on AssetCell + 'Where used' tab on detail drawer.
  usageMap: Map<string, number>;
}

// --- Prop slices ---

export interface TypePillsProps {
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  discMode: boolean;
  onTypeChange(t: MediaTypeFilter): void;
}

export interface LibraryViewProps {
  items: LibraryItem[];
  uploadQueue: UploadProgress[];
  activeType: MediaTypeFilter;
  counts: TypeCounts;
  sort: MediaSortBy;
  sortDir: SortDirection;
  gridN: 2 | 3 | 4;
  fmtFilter: string;
  selMode: boolean;
  selectedKeys: Set<string>;
  searchQuery: string;
  /** All folders flat — for §14 Move-to-folder picker. */
  allFolders: MediaFolder[];
  onSort(by: MediaSortBy, dir: SortDirection): void;
  onGridN(n: 2 | 3 | 4): void;
  onFmt(f: string): void;
  onSelToggle(): void;
  onSelect(key: string): void;
  /** §14 — shift-click range select. Anchored on previous toggleSelect. */
  onShiftSelect(key: string): void;
  onSelectAll(): void;
  onRequestBulkDelete(items: LibraryItem[]): void;
  onRequestDelete(key: string): void;
  onInsert(key: string): void;
  onCtxMenu(e: React.MouseEvent, item: LibraryItem): void;
  onDetail(item: LibraryItem): void;
  /** §14 — bulk move selected assets into a folder. null = root. */
  onMoveSelected(folderId: string | null): void;
}

export type DiscOrientation = "all" | "landscape" | "portrait" | "squarish";
export type DiscColor =
  | "all"
  | "black_and_white"
  | "black"
  | "white"
  | "yellow"
  | "orange"
  | "red"
  | "purple"
  | "magenta"
  | "green"
  | "teal"
  | "blue";

export interface DiscoveryViewProps {
  activeType: MediaTypeFilter;
  photos: StockPhoto[];
  videos: StockVideo[];
  icons: DiscIcon[];
  fonts: DiscFont[];
  loading: Record<"img" | "vid" | "ico" | "fnt", boolean>;
  searchQuery: string;
  orientation: DiscOrientation;
  color: DiscColor;
  /** S19: current source provider (Unsplash / Pexels / Pixabay). */
  source?: DiscSource;
  /** S19: monthly stock-search quota strip; hidden when omitted. */
  quota?: { used: number; limit: number; upgradeHref?: string };
  onSearch(q: string, orientation?: DiscOrientation, color?: DiscColor): void;
  onSetOrientation(o: DiscOrientation): void;
  onSetColor(c: DiscColor): void;
  /** S19: switch the active stock provider; triggers a re-search. */
  onSetSource?(s: DiscSource): void;
  onLoadMore(type: "img" | "vid"): void;
  onSave(type: "img" | "vid", item: StockPhoto | StockVideo): void;
  onInsert(filename: string): void;
}

export interface UploadZoneProps {
  /** Lets a caller (the drawer footer's Upload link) open this zone's file dialog. */
  inputRef?: React.RefObject<HTMLInputElement | null>;
  /** Drawer mode (board 144:2): no drop box at rest — see UploadZone's own note. */
  compact?: boolean;
  storage: { used: number; total: number };
  onUpload(files: File[]): void;
  disabled?: boolean;
  /** Currently-uploading files. When any item has status "uploading"/"optimizing"/"processing",
   *  the zone applies med-upload-zone--uploading. Failed items render below the zone. */
  uploadQueue?: UploadProgress[];
  /** §22 — fired when user clicks Retry on a failed queue item. */
  onRetryUpload?(fileName: string): void;
  /** Quota-warn band's "Optimise images to free space ›" (board 145:199). */
  onOptimize?(): void;
}
