/**
 * Design system constants
 * @license BSD-3-Clause
 */

import type { DesignToken, StylePreset } from "./types";

export const TOKEN_CATEGORIES = {
  COLORS: "colors",
  TYPOGRAPHY: "typography",
  SPACING: "spacing",
} as const;

/**
 * V3 theme unification: cssVar fields below will be renamed from --buildrick-design-* to
 * --buildrick-design-* in P3 via codemod op 1b. Consumer hooks write whatever
 * cssVar each DesignToken carries. Chrome tokens live in themes/default.css
 * under --buildrick-*; design tokens live here.
 */
export const DEFAULT_TOKENS: DesignToken[] = [
  // Colors (9 core tokens) — groups: brand / surface / state
  {
    id: "color-primary",
    name: "Primary",
    value: "#3B82F6",
    category: "colors",
    cssVar: "--buildrick-design-color-primary",
    type: "color",
    group: "brand",
    description: "Primary brand color",
  },
  {
    id: "color-secondary",
    name: "Secondary",
    value: "#64748B",
    category: "colors",
    cssVar: "--buildrick-design-color-secondary",
    type: "color",
    group: "brand",
    description: "Secondary brand color",
  },
  {
    id: "color-accent",
    name: "Accent",
    value: "#22C55E",
    category: "colors",
    cssVar: "--buildrick-design-color-accent",
    type: "color",
    group: "brand",
    description: "Accent / highlight color",
  },
  {
    id: "color-background",
    name: "Background",
    value: "#F8FAFC",
    category: "colors",
    cssVar: "--buildrick-design-color-background",
    type: "color",
    group: "surface",
    description: "Page background",
  },
  {
    id: "color-text",
    name: "Text",
    value: "#334155",
    category: "colors",
    cssVar: "--buildrick-design-color-text",
    type: "color",
    group: "surface",
    description: "Default text color",
  },
  {
    id: "color-muted",
    name: "Muted",
    value: "#71717A",
    category: "colors",
    cssVar: "--buildrick-design-color-muted",
    type: "color",
    group: "surface",
    description: "Secondary / muted text",
  },
  {
    id: "color-border",
    name: "Border",
    value: "#27272A",
    category: "colors",
    cssVar: "--buildrick-design-color-border",
    type: "color",
    group: "surface",
    description: "Default border color",
  },
  {
    id: "color-success",
    name: "Success",
    value: "#22C55E",
    category: "colors",
    cssVar: "--buildrick-design-color-success",
    type: "color",
    group: "state",
    description: "Positive / success state",
  },
  {
    id: "color-error",
    name: "Error",
    value: "#EF4444",
    category: "colors",
    cssVar: "--buildrick-design-color-error",
    type: "color",
    group: "state",
    description: "Negative / error state",
  },
  // Typography
  {
    id: "font-heading",
    name: "Heading Font",
    value: "Inter Tight",
    category: "typography",
    cssVar: "--buildrick-design-font-heading",
    type: "font-family",
  },
  {
    id: "font-body",
    name: "Body Font",
    value: "Inter Tight",
    category: "typography",
    cssVar: "--buildrick-design-font-body",
    type: "font-family",
  },
  {
    id: "font-mono",
    name: "Mono Font",
    value: "Geist Mono",
    category: "typography",
    cssVar: "--buildrick-design-font-mono",
    type: "font-family",
  },
  {
    id: "font-size-xs",
    name: "Font XS",
    value: "12px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-xs",
    type: "font-size",
  },
  {
    id: "font-size-sm",
    name: "Font SM",
    value: "14px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-sm",
    type: "font-size",
  },
  {
    id: "font-size-base",
    name: "Font Base",
    value: "16px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-base",
    type: "font-size",
  },
  {
    id: "font-size-lg",
    name: "Font LG",
    value: "18px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-lg",
    type: "font-size",
  },
  {
    id: "font-size-xl",
    name: "Font XL",
    value: "20px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-xl",
    type: "font-size",
  },
  {
    id: "font-size-2xl",
    name: "Font 2XL",
    value: "24px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-2xl",
    type: "font-size",
  },
  {
    id: "font-size-3xl",
    name: "Font 3XL",
    value: "30px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-3xl",
    type: "font-size",
  },
  {
    id: "font-size-4xl",
    name: "Font 4XL",
    value: "36px",
    category: "typography",
    cssVar: "--buildrick-design-font-size-4xl",
    type: "font-size",
  },
  // Spacing (4px base)
  {
    id: "space-1",
    name: "Space 1",
    value: "4px",
    category: "spacing",
    cssVar: "--buildrick-design-space-1",
    type: "length",
  },
  {
    id: "space-2",
    name: "Space 2",
    value: "8px",
    category: "spacing",
    cssVar: "--buildrick-design-space-2",
    type: "length",
  },
  {
    id: "space-3",
    name: "Space 3",
    value: "12px",
    category: "spacing",
    cssVar: "--buildrick-design-space-3",
    type: "length",
  },
  {
    id: "space-4",
    name: "Space 4",
    value: "16px",
    category: "spacing",
    cssVar: "--buildrick-design-space-4",
    type: "length",
  },
  {
    id: "space-5",
    name: "Space 5",
    value: "20px",
    category: "spacing",
    cssVar: "--buildrick-design-space-5",
    type: "length",
  },
  {
    id: "space-6",
    name: "Space 6",
    value: "24px",
    category: "spacing",
    cssVar: "--buildrick-design-space-6",
    type: "length",
  },
  {
    id: "space-8",
    name: "Space 8",
    value: "32px",
    category: "spacing",
    cssVar: "--buildrick-design-space-8",
    type: "length",
  },
  {
    id: "space-10",
    name: "Space 10",
    value: "40px",
    category: "spacing",
    cssVar: "--buildrick-design-space-10",
    type: "length",
  },
  {
    id: "space-12",
    name: "Space 12",
    value: "48px",
    category: "spacing",
    cssVar: "--buildrick-design-space-12",
    type: "length",
  },
  // Effects (Radius + Shadows)
  {
    id: "radius-none",
    name: "Radius None",
    value: "0",
    category: "effects",
    cssVar: "--buildrick-design-radius-none",
    type: "length",
  },
  {
    id: "radius-sm",
    name: "Radius SM",
    value: "4px",
    category: "effects",
    cssVar: "--buildrick-design-radius-sm",
    type: "length",
  },
  {
    id: "radius-md",
    name: "Radius MD",
    value: "8px",
    category: "effects",
    cssVar: "--buildrick-design-radius-md",
    type: "length",
  },
  {
    id: "radius-lg",
    name: "Radius LG",
    value: "12px",
    category: "effects",
    cssVar: "--buildrick-design-radius-lg",
    type: "length",
  },
  {
    id: "radius-xl",
    name: "Radius XL",
    value: "16px",
    category: "effects",
    cssVar: "--buildrick-design-radius-xl",
    type: "length",
  },
  {
    id: "radius-full",
    name: "Radius Full",
    value: "9999px",
    category: "effects",
    cssVar: "--buildrick-design-radius-full",
    type: "length",
  },
  {
    id: "shadow-sm",
    name: "Shadow SM",
    value: "0 1px 2px rgba(0,0,0,0.05)",
    category: "effects",
    cssVar: "--buildrick-design-shadow-sm",
    type: "shadow",
  },
  {
    id: "shadow-md",
    name: "Shadow MD",
    value: "0 4px 6px rgba(0,0,0,0.1)",
    category: "effects",
    cssVar: "--buildrick-design-shadow-md",
    type: "shadow",
  },
  {
    id: "shadow-lg",
    name: "Shadow LG",
    value: "0 10px 15px rgba(0,0,0,0.15)",
    category: "effects",
    cssVar: "--buildrick-design-shadow-lg",
    type: "shadow",
  },
  {
    id: "shadow-xl",
    name: "Shadow XL",
    value: "0 20px 25px rgba(0,0,0,0.25)",
    category: "effects",
    cssVar: "--buildrick-design-shadow-xl",
    type: "shadow",
  },
  // Layout / Grid
  {
    id: "layout-max-width",
    name: "Container Max Width",
    value: "1280px",
    category: "layout",
    cssVar: "--buildrick-design-layout-max-width",
    type: "length",
    group: "container",
    description: "Max width of page container",
  },
  {
    id: "layout-padding-x",
    name: "Container Padding",
    value: "24px",
    category: "layout",
    cssVar: "--buildrick-design-layout-padding-x",
    type: "length",
    group: "container",
    description: "Horizontal padding on page edges",
  },
  {
    id: "layout-columns",
    name: "Grid Columns",
    value: "12",
    category: "layout",
    cssVar: "--buildrick-design-layout-columns",
    type: "number",
    group: "grid",
  },
  {
    id: "layout-gutter",
    name: "Column Gutter",
    value: "24px",
    category: "layout",
    cssVar: "--buildrick-design-layout-gutter",
    type: "length",
    group: "grid",
  },
  {
    id: "section-padding-y",
    name: "Section Padding Y",
    value: "80px",
    category: "layout",
    cssVar: "--buildrick-design-section-padding-y",
    type: "length",
    group: "sections",
  },
  {
    id: "content-max-width",
    name: "Content Max Width",
    value: "720px",
    category: "layout",
    cssVar: "--buildrick-design-content-max-width",
    type: "length",
    group: "sections",
  },
  {
    id: "base-unit",
    name: "Base Unit",
    value: "4px",
    category: "layout",
    cssVar: "--buildrick-design-base-unit",
    type: "length",
    group: "grid",
    description: "Spacing multiplier (all space tokens = N × base unit)",
  },
  {
    id: "breakpoint-mobile",
    name: "Mobile Breakpoint",
    value: "768px",
    category: "layout",
    cssVar: "--buildrick-design-breakpoint-mobile",
    type: "length",
    group: "breakpoints",
  },
  // Icons Style
  {
    id: "icon-style",
    name: "Icon Style",
    value: "outline",
    category: "icons",
    cssVar: "--buildrick-design-icon-style",
    type: "select",
    options: ["outline", "filled", "duotone"],
  },
  {
    id: "icon-stroke",
    name: "Stroke Width",
    value: "1.5",
    category: "icons",
    cssVar: "--buildrick-design-icon-stroke",
    type: "number",
    description: "SVG stroke-width for outline icons",
  },
  {
    id: "icon-size-sm",
    name: "Icon SM",
    value: "16px",
    category: "icons",
    cssVar: "--buildrick-design-icon-sm",
    type: "length",
  },
  {
    id: "icon-size-md",
    name: "Icon MD",
    value: "20px",
    category: "icons",
    cssVar: "--buildrick-design-icon-md",
    type: "length",
  },
  {
    id: "icon-size-lg",
    name: "Icon LG",
    value: "24px",
    category: "icons",
    cssVar: "--buildrick-design-icon-lg",
    type: "length",
  },
  // Buttons & CTA
  {
    id: "btn-height-sm",
    name: "Button SM Height",
    value: "32px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-height-sm",
    type: "length",
    group: "size",
  },
  {
    id: "btn-height-md",
    name: "Button MD Height",
    value: "40px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-height-md",
    type: "length",
    group: "size",
  },
  {
    id: "btn-height-lg",
    name: "Button LG Height",
    value: "48px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-height-lg",
    type: "length",
    group: "size",
  },
  {
    id: "btn-padding-x",
    name: "Button Padding X",
    value: "16px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-padding-x",
    type: "length",
    group: "style",
  },
  {
    id: "btn-font-weight",
    name: "Button Font Weight",
    value: "600",
    category: "buttons",
    cssVar: "--buildrick-design-btn-font-weight",
    type: "number",
    group: "style",
  },
  {
    id: "btn-font-size",
    name: "Button Font Size",
    value: "14px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-font-size",
    type: "font-size",
    group: "style",
  },
  {
    id: "btn-radius",
    name: "Button Radius",
    value: "8px",
    category: "buttons",
    cssVar: "--buildrick-design-btn-radius",
    type: "length",
    group: "style",
    description: "Inherits Radius MD by default",
  },
  {
    id: "cta-radius",
    name: "CTA Radius",
    value: "9999px",
    category: "buttons",
    cssVar: "--buildrick-design-cta-radius",
    type: "length",
    group: "style",
    description: "Full-pill radius for primary CTAs",
  },
  // Forms
  {
    id: "input-height",
    name: "Input Height",
    value: "40px",
    category: "forms",
    cssVar: "--buildrick-design-input-height",
    type: "length",
    group: "size",
  },
  {
    id: "input-radius",
    name: "Input Radius",
    value: "8px",
    category: "forms",
    cssVar: "--buildrick-design-input-radius",
    type: "length",
    group: "style",
  },
  {
    id: "input-border",
    name: "Input Border Color",
    value: "#27272A",
    category: "forms",
    cssVar: "--buildrick-design-input-border",
    type: "color",
    group: "style",
    description: "References Border token by default",
  },
  {
    id: "input-focus",
    name: "Input Focus Color",
    value: "#3B82F6",
    category: "forms",
    cssVar: "--buildrick-design-input-focus",
    type: "color",
    group: "style",
    description: "References Primary token by default",
  },
  {
    id: "input-padding-x",
    name: "Input Padding X",
    value: "12px",
    category: "forms",
    cssVar: "--buildrick-design-input-padding-x",
    type: "length",
    group: "size",
  },
  {
    id: "label-font-size",
    name: "Label Font Size",
    value: "13px",
    category: "forms",
    cssVar: "--buildrick-design-label-font-size",
    type: "font-size",
    group: "typography",
  },
  {
    id: "label-weight",
    name: "Label Weight",
    value: "500",
    category: "forms",
    cssVar: "--buildrick-design-label-weight",
    type: "number",
    group: "typography",
  },
  {
    id: "placeholder-color",
    name: "Placeholder Color",
    value: "#71717A",
    category: "forms",
    cssVar: "--buildrick-design-placeholder-color",
    type: "color",
    group: "style",
  },
  // Phase A.0 — placeholder defaults for 11 new kinds.
  // Spec §5.3 / Phase F starter gallery will replace these with starter-themed values.
  { id: "radius-sm", name: "Small radius", value: "4px", category: "layout", cssVar: "--bd-radius-sm", type: "length", kind: "radius", friendlyName: "Small radius" },
  { id: "radius-md", name: "Medium radius", value: "8px", category: "layout", cssVar: "--bd-radius-md", type: "length", kind: "radius", friendlyName: "Medium radius" },
  { id: "shadow-sm", name: "Small shadow", value: "0 1px 2px rgba(15,23,42,0.04)", category: "effects", cssVar: "--bd-shadow-sm", type: "shadow", kind: "shadow", friendlyName: "Small shadow" },
  { id: "shadow-md", name: "Medium shadow", value: "0 4px 12px rgba(15,23,42,0.08)", category: "effects", cssVar: "--bd-shadow-md", type: "shadow", kind: "shadow", friendlyName: "Medium shadow" },
  { id: "motion-fast", name: "Fast motion", value: "150ms ease-out", category: "effects", cssVar: "--bd-motion-fast", type: "string", kind: "motion", friendlyName: "Fast motion" },
  { id: "motion-slow", name: "Slow motion", value: "300ms ease-in-out", category: "effects", cssVar: "--bd-motion-slow", type: "string", kind: "motion", friendlyName: "Slow motion" },
  { id: "border-default", name: "Default border", value: "1px solid", category: "layout", cssVar: "--bd-border-default", type: "string", kind: "border", friendlyName: "Default border" },
  { id: "opacity-50", name: "50% opacity", value: "0.5", category: "effects", cssVar: "--bd-opacity-50", type: "number", kind: "opacity", friendlyName: "50% opacity" },
  { id: "opacity-80", name: "80% opacity", value: "0.8", category: "effects", cssVar: "--bd-opacity-80", type: "number", kind: "opacity", friendlyName: "80% opacity" },
  { id: "zindex-dropdown", name: "Dropdown z-index", value: "1000", category: "layout", cssVar: "--bd-zindex-dropdown", type: "number", kind: "zindex", friendlyName: "Dropdown z-index" },
  { id: "zindex-modal", name: "Modal z-index", value: "1050", category: "layout", cssVar: "--bd-zindex-modal", type: "number", kind: "zindex", friendlyName: "Modal z-index" },
  { id: "breakpoint-md", name: "Tablet breakpoint", value: "768px", category: "layout", cssVar: "--bd-breakpoint-md", type: "length", kind: "breakpoint", friendlyName: "Tablet breakpoint" },
  { id: "breakpoint-lg", name: "Desktop breakpoint", value: "1024px", category: "layout", cssVar: "--bd-breakpoint-lg", type: "length", kind: "breakpoint", friendlyName: "Desktop breakpoint" },
  { id: "grid-12", name: "12-column grid", value: "12", category: "layout", cssVar: "--bd-grid-12", type: "number", kind: "grid", friendlyName: "12-column grid" },
  { id: "sizing-container", name: "Container max width", value: "1200px", category: "layout", cssVar: "--bd-sizing-container", type: "length", kind: "sizing", friendlyName: "Container max width" },
  { id: "sizing-prose", name: "Prose max width", value: "65ch", category: "layout", cssVar: "--bd-sizing-prose", type: "length", kind: "sizing", friendlyName: "Prose max width" },
  { id: "icon-default", name: "Default icon size", value: "16px", category: "icons", cssVar: "--bd-icon-default", type: "length", kind: "icon", friendlyName: "Default icon size" },
  { id: "imagery-placeholder", name: "Placeholder image", value: "https://placehold.co/600x400", category: "theme", cssVar: "--bd-imagery-placeholder", type: "string", kind: "imagery", friendlyName: "Placeholder image" },
];

/**
 * Default style presets seeded into a fresh project. E4 populates this with
 * a small starter set across the 11 categories — placeholder empty array for
 * now so StylePresetRegistryProvider can boot without crashing while E2/E3
 * land first. Don't add presets here; do it in E4 with the full audit pass.
 */
export const DEFAULT_PRESETS: StylePreset[] = [];
